### ISSUE TITLE
Error: Service Unavailable

### ISSUE THREAD

**Issue by etamity** [docpad/docpad#1002]
This can take a moment...
warning: An error occurred fetching the exchange data, this is okay, but not all skeletons will be available to you
The error follows:

Error: Service Unavailable
  at Request.callback (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/index.js:792:17)
  at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/index.js:990:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickDomainCallback (node.js:381:11)

The docpad version is v6.78.3

**Comment by balupton** [comment]
Hrmm, so it's not just me. I've been looking into this the past few days, it could be an issue with bevry/feedr but not sure. Will post back when I have more details.

**Comment by etamity** [comment]
@balupton  thank you for the respond, do you have other way to install skeletons? I am new to docpad, I would like to start with a skeleton.

**Comment by balupton** [comment]
So here is the exchange file https://github.com/docpad/extras/blob/docpad-6.x/exchange.cson that we use, if you want to use them manually just clone the repo url and checkout the branch that is specified. Skeletons are just git repos.

**Comment by balupton** [comment]
Seems resolved.

**Comment by djeglin** [comment]
Seems that this issue has re-emerged, for me at least
```
warning: An error occurred fetching the exchange data, this is okay, but not all skeletons will be available to you
The error follows:

Error: Service Unavailable
  at Request.callback (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/index.js:792:17)
  at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/index.js:990:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:903:12)
  at doNTCallback2 (node.js:439:9)
  at process._tickDomainCallback (node.js:394:17)

To report the above, follow the guide at: http://docpad.org/bug-report
info: You are about to create your new project inside your current directory. Below is a list of skeletons to bootstrap your new project:

  1.	No Skeleton
  	Prefer to start from scratch? You can get started without any skeleton if you wish

Which skeleton will you use? [1-1]
  1.	No Skeleton
> %
```
This is a completely default install, so I can only assume that whatever URI is being pinged for the exchange list is unavailable for some reason?

**Comment by SteveMcArthur** [comment]
Yep - I'm seeing this. So not just you.

**Comment by ynt** [comment]
I have this issue too.

**Comment by djhmateer** [comment]
Having this issue too on a clean install of DocPad on a Win10 machine.
