### ISSUE TITLE
Error on 'docpad run' on fresh install

### ISSUE THREAD

**Issue by 16nsk** [docpad/docpad#1016]
Hi,

I have a fresh install of docpad.

I use:
* OSX 10.10 updated
* homebrew
* nodejs v0.12.7
* npm 2.14.3
* docpad v6.78.3
* git 2.5.2

The following error occurs after selecting the skeleton:

```
Error: safeps.initGitRepo: `path` option is deprecated, use `cwd` option instead.
at Object.safeps.initGitRepo (/usr/local/lib/node_modules/docpad/node_modules/safeps/out/lib/safeps.js:701:15)
  at DocPad.initGitRepo (/usr/local/lib/node_modules/docpad/out/lib/docpad.js:2948:14)
  at Task.<anonymous> (/usr/local/lib/node_modules/docpad/out/lib/docpad.js:5843:25)
  at ambi (/usr/local/lib/node_modules/docpad/node_modules/ambi/es5/lib/ambi.js:101:14)
  at Domain.fireMethod (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:397:23)
  at Domain.run (domain.js:197:16)
  at Task.fire (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:435:27)
  at Immediate._onImmediate (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:452:26)
  at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Hope it helps to solve the _bug_.

Cheers.

**Comment by balupton** [comment]
Thanks. Will fix this up.

**Comment by 16nsk** [comment]
Thank you!
—
Madalin Ignisca
Passionate PHP & JS developer
Old school Devop
http://www.mgiworx.co.uk/ <http://www.mgiworx.co.uk/>
+447474401442
