### ISSUE TITLE
Error when run on Windows

### ISSUE THREAD

**Issue by Sogl** [docpad/docpad#1024]
Hi!

I tried to start project on docpad but see this error:
```
$ docpad run
An error occured within the child DocPad instance: spawn C:\Users\mezin.a.AVIASHELF\AppData\Roaming\npm\node_modules ENOENT
```

How to fix this?

I use Windows 7 x64.

**Comment by Sogl** [comment]
Works with `docpad run --global`. Why I can't run it without this flag?

**Comment by SteveMcArthur** [comment]
Sounds like something is wrong with your local installation (ie - in your project) of DocPad. Try deleting the node_modules directory and then running `NPM install` in your project's root folder.

**Comment by SteveMcArthur** [comment]
Ah - if you mean you want to create a totally NEW project in an empty folder then it sounds like there is something wrong with your global installation of DocPad. `\AppData\Roaming\npm\node_modules` is normally where node's global modules (including DocPad) are installed in windows. This directory location should be on your PATH environment variable. There is sometimes problems on windows with node installations because node itself is installed in the `\Program Files\nodejs\` folder as well. So there are two global locations!. Check that `docpad.cmd` is in BOTH `\AppData\Roaming\npm\` AND `\Program Files\nodejs\`

**Comment by Sogl** [comment]
>Try deleting the node_modules directory and then running NPM install in your project's root folder.

The same error.

>Ah - if you mean you want to create a totally NEW project in an empty folder then it sounds like there is something wrong with your global installation of DocPad.

No. I'm trying to start already existing project with this command.

**Comment by SteveMcArthur** [comment]
Do you have the same problem after installing one of the skeletons?

**Comment by SteveMcArthur** [comment]
I think this issue is related to https://github.com/docpad/docpad/issues/991 and https://github.com/docpad/docpad/issues/944.

I had a similar problem a few months ago when either updating NPM or Nodejs. I think it messed up the environment paths to NPM - which is complicated in windows by being in two places. Uninstalling nodejs and NPM in the normal way doesn't seem to solve the problem as the standard uninstall process does not remove everything.

If you install skeleton no1 and this runs OK then the problem is likely with your own docpad project. If not, then there is something wrong with the global installation of docpad. My solution in this case was to completely uninstall nodejs using the following method: http://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows.

Then reinstall nodejs and docpad.

**Comment by Sogl** [comment]
>Do you have the same problem after installing one of the skeletons? Install skeleton no1 (its the simplist) and try docpad run in it's root.

Can you give a link, please? I'm new in docpad, just trying to test some existent blogs on it.
What `node` version you use? I'm on `0.12.7` just because of many bugs on Windows with `node-gyp` module.

**Comment by SteveMcArthur** [comment]
To install a skeleton just go to an empty folder and run `docpad run' and follow the instructions (assuming there's no error at that point). I'm on node 0.12.2 - but I don't think your issue is a version one.

If you get an error when executing `docpad run` in an empty folder - then your global installation of docpad is broken.

Get back to us when you've had a go at installing skeleton no1.

**Comment by Sogl** [comment]
Output:
```
$ docpad run
info: Welcome to DocPad v6.78.4 (global installation: C:\Users\mezin.a.AVIASHELF\AppData\Roaming\npm\node_modules\docpad)
notice: Please donate to DocPad or have your company sponsor it: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins:
info: Environment: development
info: Updating the exchange...
This can take a moment...
info: Updated the exchange
info: You are about to create your new project inside your current directory. Below is a list of skeletons to bootstrap your new project:

  1.    HTML5 Boilerplate (Supported)
        HTML5 Boilerplate skeleton for DocPad. Bare essentials for building a modern website with best practices

  2.    Casper (Supported)
        A port of Casper, the default theme for Ghost, to DocPad

  3.    Twitter Bootstrap (Supported)
        Simple and flexible HTML, CSS, and Javascript for popular user interface components and interactions

  4.    Twitter Bootstrap with Jade (Supported)
        Twitter Bootstrap skeleton for DocPad developed using Jade (a HAML alternative for Node.js)

  5.    Bevry's Website (Supported)
        Bevry's website - a simple landing page website with some custom routes

  6.    Benjamin Lupton's Website (Supported)
        Benjamin Lupton's website - pulls in statistics, articles, videos, and projects from around the web

  7.    DocPad's Website (Supported)
        DocPad's website - a dynamic static website that pulls in a markdown documentation repository

  8.    Bevry's Learning Centre (Supported)
        Bevry's learning centre website - a dynamic static website that pulls in a markdown documentation repository

  9.    Startup Hostel's Website (Supported)
        Startup Hostel - a static website with some dynamic routes that consolidates the social data about the nomad subscribers

  10.   Static Site Generators's Website (Supported)
        The comparison website of all the different static site generators - pulls in a yaml file that is converted to json and rendered on changes via a web hook

  11.   HTML5 Boilerplate with Jade and LESS (Unsupported)
        A skeleton that uses the HTML5 boilerplate with Jade and LESS. Also includes jQuery and the livereload plugin.

  12.   SlidePad (Unsupported)
        Create HTML5 Presentations easily with DocPad

  13.   Slides (Unsupported)
        A simple DocPad solution for generating smashing html slides.

  14.   Reveal.js (Unsupported)
        Create Reveal.js presentations easily with DocPad

  15.   Meny (Unsupported)
        Create a simple page utilizing the Meny 3D menu

  16.   Conference Boilerplate (Unsupported)
        A kickstart to create websites for conference/events

  17.   YUI PureCSS (Unsupported)
        YUI PureCSS skeleton for DocPad

  18.   Zurb Foundation (Unsupported)
        A clean responsive template that contains a logical setup for a website + blog

  19.   Zurb Foundation (Unsupported)
        A minimal Zurb Foundation skeleton with SASS and coffeescript

  20.   Casteasoft Foundation Simple Blog (Unsupported)
        This skeleton supports blog posts, clean url, posts url using date-url based, pagination on blog posts listing, and more.

  21.   No Skeleton
        Prefer to start from scratch? You can get started without any skeleton if you wish

Which skeleton will you use? [1-21]
  1.    HTML5 Boilerplate (Supported)
  2.    Casper (Supported)
  3.    Twitter Bootstrap (Supported)
  4.    Twitter Bootstrap with Jade (Supported)
  5.    Bevry's Website (Supported)
  6.    Benjamin Lupton's Website (Supported)
  7.    DocPad's Website (Supported)
  8.    Bevry's Learning Centre (Supported)
  9.    Startup Hostel's Website (Supported)
  10.   Static Site Generators's Website (Supported)
  11.   HTML5 Boilerplate with Jade and LESS (Unsupported)
  12.   SlidePad (Unsupported)
  13.   Slides (Unsupported)
  14.   Reveal.js (Unsupported)
  15.   Meny (Unsupported)
  16.   Conference Boilerplate (Unsupported)
  17.   YUI PureCSS (Unsupported)
  18.   Zurb Foundation (Unsupported)
  19.   Zurb Foundation (Unsupported)
  20.   Casteasoft Foundation Simple Blog (Unsupported)
  21.   No Skeleton
> 1
info: Installing the HTML5 Boilerplate (Supported) skeleton into c:\projects\blog_test
This can take a moment...
Initialized empty Git repository in c:/projects/blog_test/.git/
remote: Counting objects: 229, done.
rRemote: Total 229 (delta 0), reused 0 (delta 0), pack-reused 229
Receiving objects:  80% (184/229), 236.01 KiB | 169.00 KiB/s
Receiving objects: 100% (229/229), 310.24 KiB | 169.00 KiB/s, done.
Resolving deltas: 100% (74/74), done.
From https://github.com/docpad/docpad-skeleton-h5bp
 * [new branch]      docpad-6.x -> skeleton/docpad-6.x
 * [new branch]      gh-pages   -> skeleton/gh-pages
 * [new branch]      master     -> skeleton/master
From https://github.com/docpad/docpad-skeleton-h5bp
 * branch            docpad-6.x -> FETCH_HEAD
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
error: The action completed successfully
error: An error occured:

Error: Command exited with a non-zero status code.
  at Object.safeps.prepareExecutableResult (C:\Users\mezin.a.AVIASHELF\AppData\Roaming\npm\node_modules\docpad\node_modules\safeps\out\lib\safeps.js:190:24)
  at ChildProcess.<anonymous> (C:\Users\mezin.a.AVIASHELF\AppData\Roaming\npm\node_modules\docpad\node_modules\safeps\out\lib\safeps.js:322:29)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1015:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

To report the above, follow the guide at: http://docpad.org/bug-report
Error: Command exited with a non-zero status code.
  at Object.safeps.prepareExecutableResult (C:\Users\mezin.a.AVIASHELF\AppData\Roaming\npm\node_modules\docpad\node_modules\safeps\out\lib\safeps.js:190:24)
  at ChildProcess.<anonymous> (C:\Users\mezin.a.AVIASHELF\AppData\Roaming\npm\node_modules\docpad\node_modules\safeps\out\lib\safeps.js:322:29)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1015:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by SteveMcArthur** [comment]
That's telling. I think there is something wrong with your node/NPM installation. You need to do a complete uninstall and clean installation of node 0.12.7. Follow the instructions at http://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows (the accepted answer). For convenience:

>#### How to remove Node.js from Windows:

>Uninstall from Programs & Features with the uninstaller.

>Reboot (or you probably can get away with killing all node-related processes from Task Manager).

>Look for these folders and remove them (and their contents) if any still exist. Depending on the >version you installed, UAC settings, and CPU architecture, these may or may not exist:

>C:\Program Files (x86)\Nodejs
>C:\Program Files\Nodejs
>C:\Users\{User}\AppData\Roaming\npm (or %appdata%\npm)
>C:\Users\{User}\AppData\Roaming\npm-cache (or %appdata%\npm-cache)
>Check your %PATH% environment variable to ensure no references to Nodejs or npm exist.

>If it's still not uninstalled, type where node at the command prompt and you'll see where it resides ->delete that (and probably the parent directory) too.

>Reboot, for good measure.

I suspect your previous installation of node v4.x.x is causing you problems - so you need to make sure you have removed all traces of it AND your current version.
