### ISSUE TITLE
TypeError: Cannot read property 'toJSON' of null

### ISSUE THREAD

**Issue by barbalex** [docpad/docpad#1026]
This may be related to #1025 

After removing the duplicated vendor folder from the src > files folder I am left with this error when running `docpad run`:

    PS C:\Users\alex\blue-borders> docpad run
    info: Welcome to DocPad v6.78.4 (local installation: C:\Users\alex\blue-borders\node_modules\docpad)
    notice: Please donate to DocPad or have your company sponsor it: http://docpad.org/donate
    info: Contribute: http://docpad.org/docs/contribute
    info: Plugins: cleanurls, coffeescript, downloader, eco, less, livereload, marked, partials, related, stylus, text
    info: Environment: development
    info: Server started on http://0.0.0.0:9778
    info: In your web browser use http://127.0.0.1:9778
    info: LiveReload listening to new socket on channel /docpad-livereload
    undefined
    TypeError: Cannot read property 'toJSON' of null
      at Object.eval (<anonymous>:73:40)
      at Object.eval (<anonymous>:91:8)
      at eval (<anonymous>:93:6)
      at Function.eco.render (C:\Users\alex\blue-borders\node_modules\eco\lib\index.js:26:25)
      at EcoPlugin.render (C:\Users\alex\blue-borders\node_modules\docpad-plugin-eco\out\eco.plugin.js:23:32)
      at ambi (C:\Users\alex\blue-borders\node_modules\event-emitter-grouped\node_modules\ambi\out\lib\ambi.js:57:27)
      at Task.<anonymous> (C:\Users\alex\blue-borders\node_modules\event-emitter-grouped\out\lib\event-emitter-grouped.js:45
    :23)
      at ambi (C:\Users\alex\blue-borders\node_modules\ambi\es5\lib\ambi.js:101:14)
      at Domain.fireMethod (C:\Users\alex\blue-borders\node_modules\taskgroup\out\lib\taskgroup.js:397:23)
      at Domain.run (domain.js:191:14)
      at Task.fire (C:\Users\alex\blue-borders\node_modules\taskgroup\out\lib\taskgroup.js:435:27)
      at Immediate._onImmediate (C:\Users\alex\blue-borders\node_modules\taskgroup\out\lib\taskgroup.js:452:26)
      at processImmediate [as _immediateCallback] (timers.js:374:17)
    info: Generating...
    info: Downloading Bootstrap
    error: The action completed successfully
    error: Something went wrong while rendering: C:\Users\alex\blue-borders\src\render\atom.xml.eco
    The error follows:

    TypeError: Cannot read property 'toJSON' of null
      at Object.eval (<anonymous>:73:40)
      at Object.eval (<anonymous>:91:8)
      at eval (<anonymous>:93:6)
      at Function.eco.render (C:\Users\alex\blue-borders\node_modules\eco\lib\index.js:26:25)
      at EcoPlugin.render (C:\Users\alex\blue-borders\node_modules\docpad-plugin-eco\out\eco.plugin.js:23:32)
      at ambi (C:\Users\alex\blue-borders\node_modules\event-emitter-grouped\node_modules\ambi\out\lib\ambi.js:57:27)
      at Task.<anonymous> (C:\Users\alex\blue-borders\node_modules\event-emitter-grouped\out\lib\event-emitter-grouped.js:45
    :23)
      at ambi (C:\Users\alex\blue-borders\node_modules\ambi\es5\lib\ambi.js:101:14)
      at Domain.fireMethod (C:\Users\alex\blue-borders\node_modules\taskgroup\out\lib\taskgroup.js:397:23)
      at Domain.run (domain.js:191:14)
      at Task.fire (C:\Users\alex\blue-borders\node_modules\taskgroup\out\lib\taskgroup.js:435:27)
      at Immediate._onImmediate (C:\Users\alex\blue-borders\node_modules\taskgroup\out\lib\taskgroup.js:452:26)
      at processImmediate [as _immediateCallback] (timers.js:374:17)

Same error on Windows and Mac OsX.

In case it helps: This is the project: https://github.com/barbalex/blue-borders

For the record:
- Windows 10
- node v4.1.2
- npm v3.3.6
- docpad v6.78.4

**Comment by barbalex** [comment]
I could solve this issue:

the bootstrap skeleton hat built a atom.xml.eco that contained this code:

    <% for document in @getCollection('posts').toJSON(): %>

But I had removed the posts collection.

The error message did finally give me the crucial pointer but it was hidden in lots of text.
