### ISSUE TITLE
Docpad hangs on completion

### ISSUE THREAD

**Issue by pvandervelde** [docpad/docpad#1042]
When building my site with `docpad generate --env production --out c:\mydir --force --debug 6` I get the following log at the end of the process

    [32minfo:[39m Generated 138/165 files in 80.925 seconds
    [32minfo:[39m The action completed successfully
    [32minfo:[39m Shutting down... cya next time!
      Waiting on the handles:
      [ { _connecting: false,
          _hadError: false,
          _handle: null,
          _parent: null,
          _host: null,
          _readableState: 
           { objectMode: false,
             highWaterMark: 0,
             buffer: [],
             length: 0,
             pipes: null,
             pipesCount: 0,
             flowing: null,
             ended: false,
             endEmitted: false,
             reading: false,
             sync: false,
             needReadable: true,
             emittedReadable: false,
             readableListening: false,
             defaultEncoding: 'utf8',
             ranOut: false,
             awaitDrain: 0,
             readingMore: false,
             decoder: null,
             encoding: null },
          readable: false,
          domain: 
           { domain: null,
             _events: [Object],
             _maxListeners: undefined,
             members: [] },
          _events: 
           { end: [Object],
             finish: [Function: onSocketFinish],
             _socketEnd: [Function: onSocketEnd],
             pause: [Function] },
          _maxListeners: undefined,
          _writableState: 
           { objectMode: false,
             highWaterMark: 0,
             needDrain: false,
             ending: true,
             ended: true,
             finished: true,
             decodeStrings: false,
             defaultEncoding: 'utf8',
             length: 0,
             writing: false,
             corked: 0,
             sync: true,
             bufferProcessing: false,
             onwrite: [Function],
             writecb: null,
             writelen: 0,
             bufferedRequest: null,
             lastBufferedRequest: null,
             pendingcb: 0,
             prefinished: true,
             errorEmitted: false },
          writable: false,
          allowHalfOpen: false,
          destroyed: true,
          bytesRead: 0,
          _bytesDispatched: 0,
          _writev: null,
          _pendingData: null,
          _pendingEncoding: '',
          isRaw: false,
          isTTY: true,
          fd: 0,
          _idleNext: null,
          _idlePrev: null,
          _idleTimeout: -1 } ]

After this the docpad / node process just sits idle but never exits. It looks to me that it is waiting for something that will never happen.

My package.json file looks like

	{
	  "name": "mindvortex.docpad",
	  "version": "0.1.0",
	  "private": true,
	  "description": "Patrick van der Velde's personal web page.",
	  "homepage": "http://petrikvandervelde.nl",
	  "keywords": [
		"docpad-skeleton",
		"docpad",
		"website",
		"skeleton",
		"html5 boilerplate",
		"h5bp"
	  ],
	  "author": "Patrick van der Velde (http://petrikvandervelde.nl)",
	  "maintainers": [
		"Patrick van der Velde (http://petrikvandervelde.nl)"
	  ],
	  "contributors": [
		"Patrick van der Velde (http://petrikvandervelde.nl)"
	  ],
	  "repository": {
		"type": "git",
		"url": "https://github.com/pvandervelde/mindvortex.git"
	  },
	  "engines": {
		"node": "0.12.x",
		"npm": "3.5.x"
	  },
	  "dependencies": {
		"docpad": "~6.78.4",
		"docpad-plugin-coffeescript": "~2.5.0",
		"docpad-plugin-datefromfilename": "~2.0.4",
		"docpad-plugin-eco": "~2.1.0",
		"docpad-plugin-gist": "~2.1.1",
		"docpad-plugin-highlightjs": "~2.3.0",
		"docpad-plugin-marked": "~2.3.0",
		"docpad-plugin-navlinks": "~2.0.4",
		"docpad-plugin-paged": "~2.4.0",
		"docpad-plugin-partials": "~2.9.2",
		"docpad-plugin-related": "~2.2.2",
		"docpad-plugin-sitemap": "~2.2.0",
		"docpad-plugin-stylus": "~2.11.0",
		"docpad-plugin-tagcloud": "~2.0.1",
		"docpad-plugin-tags": "~2.0.7",
		"docpad-plugin-text": "~2.3.3",
		"eco": "~1.1.0-rc-3",
		"moment": "~2.12.0"
	  },
	  "devDependencies": {
		"docpad-plugin-livereload": "~2.7.1",
		"docpad-plugin-services": "~2.6.0"
	  },
	  "main": "node_modules/docpad/bin/docpad-server"
	}

I've tried node 0.12.7, 4.1.1. and 5.3.0 and all of them do the same thing. Is there anything I can do to make docpad / node complete the process?

**Comment by pvandervelde** [comment]
Anybody have any idea about this one? Is this a docpad issue or a node.js issue?

**Comment by almereyda** [comment]
I am getting the same effect. It MAY be affected to https://github.com/docpad/docpad/issues/192, but I am not sure, yet.

After

    npm update --save

it got even worse:

```
  _httpMessage: 
     ClientRequest {
       domain: [Object],
       _events: [Object],
       _eventsCount: 3,
       _maxListeners: undefined,
       output: [],
       outputEncodings: [],
       outputCallbacks: [],
       outputSize: 0,
       writable: true,
       _last: true,
       chunkedEncoding: false,
       shouldKeepAlive: false,
       useChunkedEncodingByDefault: true,
       sendDate: false,
       _removedHeader: [Object],
       _contentLength: 17742,
       _hasBody: true,
       _trailer: '',
       finished: true,
       _headerSent: true,
       socket: [Circular],
       connection: [Circular],
       _header: 'POST /?method=analytics&action=track HTTP/1.1\r\nHost: helper.docpad.org\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.8.3\r\nContent-Type: application/json\r\nAccept: application/json\r\nContent-Length: 17742\r\nConnection: close\r\n\r\n',
       _headers: [Object],
       _headerNames: [Object],
       _onPendingData: null,
       agent: [Object],
       socketPath: undefined,
       method: 'POST',
       path: '/?method=analytics&action=track',
       parser: [Object] },
    read: [Function],
    _consuming: true },
  Timer {
    '0': [Function: listOnTimeout],
    _idleNext: 
     { _called: false,
       _idleTimeout: 30000,
       _idlePrev: [Circular],
       _idleNext: [Circular],
       _idleStart: 32564,
       _onTimeout: [Function],
       _repeat: null,
       domain: [Object] },
    _idlePrev: 
     { _called: false,
       _idleTimeout: 30000,
       _idlePrev: [Circular],
       _idleNext: [Circular],
       _idleStart: 32564,
       _onTimeout: [Function],
       _repeat: null,
       domain: [Object] },
    msecs: 30000 } ]
Error: The task [generate] just completed, but it had already completed earlier, this is unexpected. State information is:
{ error: 'Error: The task [generate tasks ➞  fetch data to render ➞  taskgroup method for fetch data to render] just completed, but it had already completed earlier, this is unexpected. State information is:\n{ error: \'Error: The task [generate tasks ➞  fetch data to render ➞  import data from file system ➞  taskgroup method for import data from file system] just completed, but it had already completed earlier, this is unexpected. State information is:\\n{ error: \\\'Error: The task [generate tasks ➞  fetch data to render ➞  import data from file system ➞  import files] just completed, but it had already completed earlier, this is unexpected. State information is:\\\\n{ error: \\\\\\\'Error: The task [taskgroup 0.1319572082720697 ➞  task 8 for taskgroup 0.1319572082720697] just completed, but it had already completed earlier, this is unexpected. State information is:\\\\\\\\n{ error: \\\\\\\\\\\\\\\'Error: The task [taskgroup 0.1523737940005958 ➞  task 1 for taskgroup 0.1523737940005958] just completed, but it had already completed earlier, this is unexpected. State information is:\\\\\\\\\\\\\\\\n{ error: \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'Error: The task [taskgroup 0.257791418582201 ➞  task 8 for taskgroup 0.257791418582201] just completed, but it had already completed earlier, this is unexpected. State information is:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n{ error: \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'Error: write after end\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at writeAfterEnd (_stream_writable.js:159:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Logger.Writable.write (_stream_writable.js:204:5)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Logger.log (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/caterpillar/out/lib/caterpillar.js:225:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Logger.log (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/caterpillar/out/lib/caterpillar.js:4:61)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at DocPad.log (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/docpad/out/lib/docpad.js:3258:18)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at _Class.<anonymous> (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/docpad/out/lib/docpad.js:1898:29)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at emitTwo (events.js:87:13)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at _Class.emit (events.js:172:7)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.<anonymous> (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:753:26)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at emitOne (events.js:82:20)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.emit (events.js:169:7)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.<anonymous> (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:53:28)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at emitOne (events.js:82:20)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.emit (events.js:169:7)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.complete (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:319:19)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.exit (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:301:14)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at complete (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:388:26)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at /srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/docpad/out/lib/docpad.js:3561:20\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at /srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/docpad/out/lib/docpad.js:3480:16\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Request.callback (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/superagent/lib/node/index.js:691:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Stream.<anonymous> (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/superagent/lib/node/index.js:922:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at emitNone (events.js:72:20)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Stream.emit (events.js:166:7)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Unzip.<anonymous> (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/superagent/lib/node/utils.js:108:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at emitNone (events.js:72:20)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Unzip.emit (events.js:166:7)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at endReadableNT (_stream_readable.js:905:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at nextTickCallbackWith2Args (node.js:437:9)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at process._tickDomainCallback (node.js:392:17)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\',\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  previousResult: [],\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  currentArguments: [ { [Error: write after end] domain: [Object], domainThrown: true } ] }\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.exit (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:309:15)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at emitOne (events.js:77:13)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Domain.emit (events.js:169:7)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at emitError (domain.js:66:24)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Domain.errorHandler [as _errorHandler] (domain.js:126:16)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at process._fatalException (node.js:216:33)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\',\\\\\\\\\\\\\\\\n  previousResult: [],\\\\\\\\\\\\\\\\n  currentArguments: \\\\\\\\\\\\\\\\n   [ { [Error: The task [taskgroup 0.257791418582201 ➞  task 8 for taskgroup 0.257791418582201] just completed, but it had already completed earlier, this is unexpected. State information is:\\\\\\\\\\\\\\\\n     { error: \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'Error: write after end\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at writeAfterEnd (_stream_writable.js:159:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Logger.Writable.write (_stream_writable.js:204:5)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Logger.log (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/caterpillar/out/lib/caterpillar.js:225:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Logger.log (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/caterpillar/out/lib/caterpillar.js:4:61)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at DocPad.log (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/docpad/out/lib/docpad.js:3258:18)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at _Class.<anonymous> (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/docpad/out/lib/docpad.js:1898:29)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at emitTwo (events.js:87:13)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at _Class.emit (events.js:172:7)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.<anonymous> (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:753:26)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at emitOne (events.js:82:20)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.emit (events.js:169:7)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.<anonymous> (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:53:28)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at emitOne (events.js:82:20)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.emit (events.js:169:7)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.complete (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:319:19)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Task.exit (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:301:14)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at complete (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:388:26)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at /srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/docpad/out/lib/docpad.js:3561:20\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at /srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/docpad/out/lib/docpad.js:3480:16\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Request.callback (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/superagent/lib/node/index.js:691:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Stream.<anonymous> (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/superagent/lib/node/index.js:922:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at emitNone (events.js:72:20)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Stream.emit (events.js:166:7)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Unzip.<anonymous> (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/superagent/lib/node/utils.js:108:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at emitNone (events.js:72:20)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Unzip.emit (events.js:166:7)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at endReadableNT (_stream_readable.js:905:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at nextTickCallbackWith2Args (node.js:437:9)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at process._tickDomainCallback (node.js:392:17)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\',\\\\\\\\\\\\\\\\n       previousResult: [],\\\\\\\\\\\\\\\\n       currentArguments: [ { [Error: write after end] domain: [Object], domainThrown: true } ] }]\\\\\\\\\\\\\\\\n       domainEmitter: [Object],\\\\\\\\\\\\\\\\n       domain: [Object],\\\\\\\\\\\\\\\\n       domainThrown: false } ] }\\\\\\\\\\\\\\\\n  at Task.exit (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:309:15)\\\\\\\\\\\\\\\\n  at emitOne (events.js:77:13)\\\\\\\\\\\\\\\\n  at Domain.emit (events.js:169:7)\\\\\\\\\\\\\\\\n  at Task.emit (events.js:139:14)\\\\\\\\\\\\\\\\n  at Task.exit (/srv/git/Fundus/github.com/TransforMap/transformap.github.io/node_modules/taskgroup/out/lib/taskgroup.js:310:14)\\\\\\\\\\\\\\\\n  at emitOne (events.js:77:13)\\\\\\\\\\\\\\\\n  at Domain.emit (events.js:169:7)\\\\\\\\\\\\\\\\n  at emitError (domain.js:66:24)\\\\\\\\\\\\\\\\n  at Domain.errorHandler [as _errorHandler] (domain.js:126:16)\\\\\\\\\\\\\\\\n  at process._fatalException (node.js:216:33)\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\',\\\\\\\\n  previousResult: [],\\\\\\\\n  currentArguments: \\\\\\\\n   [ { [Error: The task [taskgroup 0.1523737940005958 ➞  task 1 for taskgroup 0.1523737940005958] just completed, but it had already completed earlier, this is unexpected. State information is:\\\\\\\\n     { error: \\\\\\\\\\\\\\\'Error: The task [taskgroup 0.257791418582201 ➞  task 8 for taskgroup 0.257791418582201] just completed, but it had already completed earlier, this is unexpected. State information is:\\\\\\\\\\\\\\\\n{ error: \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'Error: write after end\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at writeAfterEnd (_stream_writable.js:159:12)\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n  at Logger.Writable.write (_stream_wri
<--- Last few GCs --->

   55906 ms: Scavenge 1420.9 (1472.6) -> 1420.9 (1472.6) MB, 0.1 / 0 ms (+ 0.0 ms in 2 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   55958 ms: Mark-sweep 1420.9 (1472.6) -> 1385.8 (1437.5) MB, 51.9 / 0 ms (+ 2.8 ms in 5 steps since start of marking, biggest step 1.8 ms) [last resort gc].
   56002 ms: Mark-sweep 1385.8 (1437.5) -> 1385.8 (1437.5) MB, 43.8 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2b7d530b4629 <JS Object>
    1: replace(aka replace) [native string.js:~146] [pc=0x28e20e35b00] (this=0x302ccd4ef951 <Very long string[136821]>,N=0x2c6ec73fd7f1 <JS RegExp>,O=0x2b7d53004291 <String[0]: >)
    2: /* anonymous */(aka /* anonymous */) [util.js:617] [pc=0x28e20f27cbd] (this=0x2b7d530041b9 <undefined>,prev=0,cur=0x302ccd4ef951 <Very long string[136821]>)
    3: arguments adaptor frame: 4->2
    4: InnerArra...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abgebrochen (Speicherabzug geschrieben)
```

which makes me suspect this is connected partly to the @BevryMe infrastructure running docpad-related web services. This happened with Node 4.3.1 for me. Any ideas @balupton?

**Comment by almereyda** [comment]
This had been generated with

```
npm ERR! Linux 4.4.9-200.fc22.x86_64
npm ERR! argv "/home/almereyda/.nvm/versions/node/v4.3.1/bin/node" "/home/almereyda/.nvm/versions/node/v4.3.1/bin/npm" "install" "0.10.45"
npm ERR! node v4.3.1
npm ERR! npm  v3.7.5
```

while

```
npm ERR! Linux 4.4.9-200.fc22.x86_64
npm ERR! argv "/home/almereyda/.nvm/v0.10.45/bin/node" "/home/almereyda/.nvm/v0.10.45/bin/npm" "whoami"
npm ERR! node v0.10.45
npm ERR! npm  v2.15.1
```

turned out to crash only more verbose.

**Comment by almereyda** [comment]
This didn't appear anymore with Node.js 0.12, as 0.10 (https://github.com/docpad/docpad/blob/master/package.json#L138) was a little too low for plenty meanwhile updated dependencies.

**Comment by sdomagala** [comment]
This stacktrace is appearing if you run out of memory, so:
- there might be too many documents to render and it fails to load them to memory, in this case node flag `max_old_space_size` can be used (but you can't use `docpad` keyword).
Command I use:
```
node --max-old-space-size=8192 --max-semi-space-size=512 --nouse-idle-notification node_modules/docpad/out/bin/docpad-server.js
```
- infinite loop - there is probably some document that is causing this failure.

**Comment by pvandervelde** [comment]
My original issue doesn't seem to be having memory issues. It seems more to be a deadlock or something in that order.

**Comment by Kikketer** [comment]
I'm getting the exact same issue.  When I run "docpad generate" I get the long hang (if you wait long enough it gives up).  DocPad has always had issues with this, to a point where my team simply runs "docpad run" and kills it manually.  Been dealing with this for years... seriously.

Anyway, here's what I have:
Mac
Node: 5.10.1
DocPad version: v6.78.6

**Comment by DenEwout** [comment]
Hi, I'm having the same issue.

**Comment by balupton** [comment]
Took a bit longer than expected. But v6.80.7 is now out.
