### ISSUE TITLE
Docpad.action('generate') fails when user has no $HOME directory

### ISSUE THREAD

**Issue by CameronAM** [docpad/docpad#1054]
I'm running docpad as part of an AWS Lambda function, I am getting the following exception when running docpad.action('generate')

```
TypeError: Path must be a string. Received null
  at assertPath (path.js:8:11)
  at Object.posix.resolve (path.js:426:5)
  at /var/task/node_modules/docpad/out/lib/docpad.js:2574:34
  at Object.safeps.getHomePath (/var/task/node_modules/safeps/out/lib/safeps.js:555:7)
  at Task.<anonymous> (/var/task/node_modules/docpad/out/lib/docpad.js:2569:23)
  at ambi (/var/task/node_modules/ambi/es2015/index.js:97:14)
  at Domain.fireMethod (/var/task/node_modules/taskgroup/out/lib/taskgroup.js:397:23)
  at Domain.run (domain.js:228:14)
  at Task.fire (/var/task/node_modules/taskgroup/out/lib/taskgroup.js:435:27)
  at Immediate._onImmediate (/var/task/node_modules/taskgroup/out/lib/taskgroup.js:452:26)
  at processImmediate [as _immediateCallback] (timers.js:383:17)
```

It seems to be happening because docpad is attempting to lookup the home dir for the current user, but here is NO user when executing in the lambda environment.

Is it possible to configure this check out, or to have it not fail where a user has no home directory?

**Comment by balupton** [comment]
Hrmmm, that is strange. Perhaps set the home directory to be something. From memory I can't remember what it is that needs this directory to be defined - perhaps for the global configuration file. However, yeah, it shouldn't be a failure if not defined.

Removing the analytics should help with this https://github.com/docpad/docpad/issues/1041

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
