### ISSUE TITLE
Docpad break with Node 9.2

### ISSUE THREAD

**Issue by nylnook** [docpad/docpad#1068]
Hi,

I'm happily using Docpad on [my website](https://nylnook.art) since 2014 ([repo available here](https://github.com/nylnook/nylnook-website/))...thanks for your immense work!
I'm using it on Archlinux, and until now nodejs was the packaged version, now updated to 9.2...

This is probably linked to #1065, but upgrading to 9.2 broke Docpad for me:
```
$ docpad run
warning: docpad-plugin-paged: getPageUrl is deprecated and may clash with other plugins. Use getPagedUrl instead.
info: Welcome to DocPad v6.79.4 (local installation: /home/nylnook/Crea/nylnook-website/node_modules/docpad)
notice: Please donate to DocPad or have your company sponsor it: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: cleanurls, coffeescript, eco, highlightjs, livereload, marked, paged, partials, rss, sitemap, stylus
info: Environment: development
info: LiveReload listening to new socket on channel /docpad-livereload
info: Server started on http://0.0.0.0:8080
info: In your web browser use http://127.0.0.1:8080
TypeError: me._domain.dispose is not a function
    at /home/nylnook/Crea/nylnook-website/node_modules/progressbar/source/index.js:1:1
    at ProgressBar.destroy (/home/nylnook/Crea/nylnook-website/node_modules/progressbar/source/index.js:1:1)
    at ProgressBar.finish (/home/nylnook/Crea/nylnook-website/node_modules/progressbar/source/index.js:1:1)
    at DocPad.destroyProgress (/home/nylnook/Crea/nylnook-website/node_modules/docpad/out/lib/docpad.js:1:1)
    at _Class.<anonymous> (/home/nylnook/Crea/nylnook-website/node_modules/docpad/out/lib/docpad.js:1:1)
    at Object.onceWrapper (events.js:1:1)
    at _Class.emit (events.js:1:1)
    at _Class.<anonymous> (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:48:16)
    at _Class.emit (events.js:1:1)
    at _Class.TaskGroup.complete (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:1:1)
    at _Class.TaskGroup.exit (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:1:1)
    at _Class.TaskGroup.fire (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:1:1)
    at _Class.TaskGroup.itemCompletionCallback (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:1:1)
    at Task.<anonymous> (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:1:1)
    at Object.onceWrapper (events.js:1:1)
    at Task.emit (events.js:1:1)
    at Task.<anonymous> (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:48:16)
    at Task.emit (events.js:1:1)
    at Task.complete (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:1:1)
    at Task.exit (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:1:1)
    at complete (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:1:1)
    at Task.<anonymous> (/home/nylnook/Crea/nylnook-website/node_modules/docpad/out/lib/docpad.js:1:1)
    at ambi (/home/nylnook/Crea/nylnook-website/node_modules/ambi/source/index.js:1:1)
    at Domain.fireMethod (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:1:1)
    at Domain.run (domain.js:1:1)
    at Task.fire (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:1:1)
    at Immediate.<anonymous> (/home/nylnook/Crea/nylnook-website/node_modules/taskgroup/out/lib/taskgroup.js:1:1)
    at runCallback (timers.js:1:1)
    at tryOnImmediate (timers.js:1:1)
    at processImmediate [as _immediateCallback] (timers.js:1:1)
```

If I downgrade to nodejs 8.9.1 with NVM, Docpad run smoothly...

Maybe this should be mentioned on the DocPad installation page waiting for a fix...

My best regards,

**Comment by Aglezabad** [comment]
It's failing in progressbar. Maybe due to deprecation of some Node.js functions. I will check that if I can do a fix.

**Comment by nylnook** [comment]
Great, thank you !

**Comment by Aglezabad** [comment]
There's already a PR on progressbar which removes everything related with domains. I'm waiting for review.

Regards.

**Comment by balupton** [comment]
progressbar change has been done

dep upgrade to docpad should be in `6.80.0-beta`

**Comment by jlukic** [comment]
There's kind of a catch 22 currently where some common community plugins (babel, copy) break with `6.80` but recent versions of node break with old Docpad. 

Would love if this fix was backported, or the core docpad plugins were fixed.

**Comment by balupton** [comment]
@jlukic any time I invest into docpad is a loss for me, so happy to show you what is needed to do compat if you book a time on https://balupton.com/meet - it's mostly just running some automated scripts on old plugins and fixing some dep update breaking changes (notably task group api changes)

**Comment by jlukic** [comment]
Yeah I understand completely. Didn't mean to grief ya. Will see what i can do.

**Comment by balupton** [comment]
@jlukic I spent today blasting through the automations, got some new releases out, still some left
