### ISSUE TITLE
Docpad run operation could not be successfully completed due to Error: Service Unavailable 

### ISSUE THREAD

**Issue by FreakyMaryk** [docpad/docpad#1075]
Hello, I could not run normally docpad! Please, fix an error!

docpad run 
info: Welcome to DocPad v6.79.4 (global installation: *\AppData\Roaming\npm\node_modules\docpad) 
notice: Please donate to DocPad or have your company sponsor it: http://docpad.org/donate 
info: Contribute: http://docpad.org/docs/contribute 
info: Plugins: 
info: Environment: development 
info: Updating the exchange... 
This can take a moment... 
warning: An error occurred fetching the exchange data, this is okay, but not all skeletons will be available to you 
The error follows: 

Error: Service Unavailable 
at Request.callback (*\AppData\Roaming\npm\node_modules\docpad\node_modules\superagent\lib\node\index.js:698:17) 
at IncomingMessage.<anonymous> (*\AppData\Roaming\npm\node_modules\docpad\node_modules\superagent\lib\node\index.js:922:12) 
at IncomingMessage.emit (events.js:187:15) 
at IncomingMessage.EventEmitter.emit (domain.js:460:23) 
at endReadableNT (_stream_readable.js:1090:12) 
at process._tickCallback (internal/process/next_tick.js:63:19) 

To report the above, follow the guide at: http://docpad.org/bug-report

**Comment by balupton** [comment]
Yeah the remote helper crashed. Run it with the `--offline` flag.

**Comment by balupton** [comment]
Figured out the cause: https://npm.community/t/how-do-i-fetch-all-npm-packages-that-contain-a-given-keyword/400?u=balupton

**Comment by balupton** [comment]
The service should now exist
