### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#1082]
Occurs with `docpad render` command when using stdin. Seems to be node.js version dependent, as the code for this hasn't changed.

```
A fatal error occured within DocPad: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.basename (path.js:1299:5)
    at ConsoleInterface.render (/Users/balupton/Projects/docpad/docpad/esnext/lib/interfaces/console.js:618:25)
    at /Users/balupton/Projects/docpad/docpad/esnext/lib/interfaces/console.js:361:14
    at TaskGroup.<anonymous> (/Users/balupton/Projects/docpad/docpad/esnext/lib/util.js:388:11)
    at Object.onceWrapper (events.js:273:13)
    at TaskGroup.emit (events.js:182:13)
    at TaskGroup.EventEmitter.emit (domain.js:442:20)
    at TaskGroup.listener (/Users/balupton/Projects/active/taskgroup/source/lib/interface.js:61:10)
    at TaskGroup.emit (events.js:182:13)
    at TaskGroup.EventEmitter.emit (domain.js:442:20)
    at TaskGroup.finish (/Users/balupton/Projects/active/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/Users/balupton/Projects/active/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/Users/balupton/Projects/active/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:273:13)
    at Task.emit (events.js:187:15)
    at Task.EventEmitter.emit (domain.js:442:20)
    at Task.listener (/Users/balupton/Projects/active/taskgroup/source/lib/interface.js:61:10)
    at Task.emit (events.js:182:13)
    at Task.EventEmitter.emit (domain.js:442:20)
    at Task.finish (/Users/balupton/Projects/active/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/Users/balupton/Projects/active/taskgroup/source/lib/task.js:375:8)
    at completeMethod (/Users/balupton/Projects/active/taskgroup/source/lib/task.js:507:5)
    at TaskGroup.next (/Users/balupton/Projects/docpad/docpad/esnext/lib/docpad.js:1892:47)
    at Object.onceWrapper (events.js:273:13)
    at TaskGroup.emit (events.js:182:13)
    at TaskGroup.EventEmitter.emit (domain.js:460:23)
    at TaskGroup.listener (/Users/balupton/Projects/active/taskgroup/source/lib/interface.js:61:10)
    at TaskGroup.emit (events.js:182:13)
    at TaskGroup.EventEmitter.emit (domain.js:460:23)
    at TaskGroup.finish (/Users/balupton/Projects/active/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/Users/balupton/Projects/active/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/Users/balupton/Projects/active/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:273:13)
    at Task.emit (events.js:187:15)
    at Task.EventEmitter.emit (domain.js:460:23)
    at Task.listener (/Users/balupton/Projects/active/taskgroup/source/lib/interface.js:61:10)
    at Task.emit (events.js:182:13)
    at Task.EventEmitter.emit (domain.js:460:23)
    at Task.finish (/Users/balupton/Projects/active/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/Users/balupton/Projects/active/taskgroup/source/lib/task.js:375:8)
    at completeMethod (/Users/balupton/Projects/active/taskgroup/source/lib/task.js:507:5)
    at TaskGroup.<anonymous> (/Users/balupton/Projects/docpad/docpad/esnext/lib/docpad.js:1700:16)
    at Object.onceWrapper (events.js:273:13)
    at TaskGroup.emit (events.js:182:13)
    at TaskGroup.EventEmitter.emit (domain.js:460:23)
    at TaskGroup.listener (/Users/balupton/Projects/active/taskgroup/source/lib/interface.js:61:10)
    at TaskGroup.emit (events.js:182:13)
    at TaskGroup.EventEmitter.emit (domain.js:460:23)
    at TaskGroup.finish (/Users/balupton/Projects/active/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/Users/balupton/Projects/active/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/Users/balupton/Projects/active/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:273:13)
    at Task.emit (events.js:187:15)
    at Task.EventEmitter.emit (domain.js:460:23)
    at Task.listener (/Users/balupton/Projects/active/taskgroup/source/lib/interface.js:61:10)
    at Task.emit (events.js:182:13)
    at Task.EventEmitter.emit (domain.js:460:23)
    at Task.finish (/Users/balupton/Projects/active/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/Users/balupton/Projects/active/taskgroup/source/lib/task.js:375:8)
    at completeMethod (/Users/balupton/Projects/active/taskgroup/source/lib/task.js:507:5)
    at DocPad.<anonymous> (/Users/balupton/Projects/docpad/docpad/esnext/lib/docpad.js:1414:20)
    at ambi (/Users/balupton/Projects/active/taskgroup/node_modules/ambi/source/index.js:74:3)
    at Domain.fireMethod (/Users/balupton/Projects/active/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:343:14)
    at Task.fire (/Users/balupton/Projects/active/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue (/Users/balupton/Projects/active/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
```

**Comment by balupton** [comment]
v6.80.7 is now out which resolves this
