### ISSUE TITLE
Error: Cannot find module 'editions'

### ISSUE THREAD

**Issue by dstack** [docpad/docpad#1088]
Fresh install of docpad, locally or globally, I get the same error.

docpad: 6.81.0 and 6.80.9
node: 10.9.0
npm: 6.4.0
Windows 10

Error: Cannot find module 'editions'                                           
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)           
    at Module.require (internal/modules/cjs/loader.js:637:17)                  
    at require (internal/modules/cjs/helpers.js:20:18)                         
    at Object.<anonymous> (D:\Apps\dscom5\node_modules\docpad\bin.js:2:18)     
    at Module._compile (internal/modules/cjs/loader.js:689:30)                 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)   
    at Module.load (internal/modules/cjs/loader.js:599:32)                     
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)                   
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)            

 This specific example is from "docpad init" but I get the same running "docpad -v", really anything with docpad.

**Comment by balupton** [comment]
See https://npm.community/t/packages-published-on-unix-with-in-filenames-fail-to-be-required-on-windows/1682?u=balupton for details

**Comment by dstack** [comment]
Thanks @balupton 👍 .

For anyone else that runs into this on windows, falling back to docpad@6.79.0 resolves this.

**Comment by balupton** [comment]
this should now be resolved
