### ISSUE TITLE
DocPad.fatal at docpad/edition-esnext/lib/docpad.js

### ISSUE THREAD

**Issue by mikeumus** [docpad/docpad#1092]
Attempting to upgrade Mikeumus.com to DocPad v6.82.1 but getting this:

``` bash
mmooring@M-C02VW070HTDG ~/Documents/Mikeumus/code/mikeumus.docpad                                          [13:50:58] 
> $ docpad run                                                                                           [±master ●●]
info: Welcome to DocPad v6.82.1 (global installation: /usr/local/lib/node_modules/docpad)
notice: Please donate to DocPad or have your company sponsor it: https://docpad.org/donate
info: Contribute: https://docpad.org/docs/contribute
info: Plugins: coffeescript, downloader, eco, ghpages, less, marked, partials, related, services, stylus, text
info: Environment: development
notice: Set the exit code from unset to 1 because of fatal from: A fatal error occured within DocPad
critical: Error: A fatal error occured within DocPad
    at DocPad.fatal (/usr/local/lib/node_modules/docpad/edition-esnext/lib/docpad.js:2756:13)
    at /usr/local/lib/node_modules/docpad/edition-esnext/lib/cli.js:206:23
    at TaskGroup.<anonymous> (/usr/local/lib/node_modules/docpad/edition-esnext/lib/docpad.js:1407:18)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at TaskGroup.emit (events.js:214:7)
    at TaskGroup.listener (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at emitTwo (events.js:126:13)
    at TaskGroup.emit (events.js:214:7)
    at TaskGroup.finish (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at Task.emit (events.js:211:7)
    at Task.listener (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at emitOne (events.js:116:13)
    at Task.emit (events.js:211:7)
    at Task.finish (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:375:8)
    at emitOne (events.js:116:13)
    at Domain.emit (events.js:211:7)
    at Domain._errorHandler (domain.js:134:21)
    at process._fatalException (bootstrap_node.js:375:33)

↳ TypeError: Cannot read property 'command' of undefined
    at GhpagesPlugin.consoleSetup (/Users/mmooring/Documents/Mikeumus/code/mikeumus.docpad/node_modules/docpad-plugin-ghpages/esnext/ghpages.plugin.js:178:19)
    at ambi (/usr/local/lib/node_modules/docpad/node_modules/ambi/source/index.js:81:18)
    at Domain.fireMethod (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:242:14)
    at Task.fire (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue [as _onImmediate] (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

Please report it using this guide: https://docpad.org/bug-report
info: DocPad is shutting down...
Shutdown complete. See you next time.
```

Here's the branch: https://github.com/mikeumus/mikeumus.docpad/tree/docpad-v6.82.1

All plugins have been updated. 

Should I add [Boundation](https://github.com/bevry/boundation) and try with that?

**Comment by mikeumus** [comment]
> so 6.82 will break the ghpages plugin
Uninstall that plugin and you will be good to go
~ @balupton

**Comment by lubber-de** [comment]
2.11.0 fixes it. Unfortunately is is not deployed to npm, so add the github tag directly 
```json
  "devDependencies": {
    "docpad-plugin-ghpages": "github:docpad/docpad-plugin-ghpages#2.11.0"
  }
```
