### ISSUE TITLE
I'm picking up an existing project using docpad, not sure if this is a bug?

### ISSUE THREAD

**Issue by MartynCook** [docpad/docpad#1095]
I followed the install docs, thought it was a node issue at first so I've switched to an older version. Anyone know if this is a build issue or docpad issue? 

I've followed the docs here **https://docpad.org/docs/install**

`$docpad -v`

// responce 

```
debug: load tasks ➞  update the configurations > done
    → [2018-12-17 09:37:11.621] [events.js:272] [Object.onceWrapper]
debug: The plugin [/Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-babel] was resolved indirectly
    → [2018-12-17 09:37:12.062] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/@bevry/pluginloader/source/index.js:173] [new PluginLoader]
debug: Loading plugin: /Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-babel
    → [2018-12-17 09:37:12.064] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308] [Task.<anonymous>]
debug: The plugin [/Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-copy] was resolved indirectly
    → [2018-12-17 09:37:12.068] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/@bevry/pluginloader/source/index.js:173] [new PluginLoader]
debug: Loading plugin: /Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-copy
    → [2018-12-17 09:37:12.069] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308] [Task.<anonymous>]
debug: The plugin [/Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-eco] was resolved indirectly
    → [2018-12-17 09:37:12.076] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/@bevry/pluginloader/source/index.js:173] [new PluginLoader]
debug: Loading plugin: /Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-eco
    → [2018-12-17 09:37:12.077] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308] [Task.<anonymous>]
debug: Loaded plugin: /Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-eco
    → [2018-12-17 09:37:12.078] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308] [Task.<anonymous>]
debug: The plugin [/Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-partials] was resolved indirectly
    → [2018-12-17 09:37:12.126] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/@bevry/pluginloader/source/index.js:173] [new PluginLoader]
debug: Loading plugin: /Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-partials
    → [2018-12-17 09:37:12.127] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308] [Task.<anonymous>]
debug: Loaded plugin: /Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-partials
    → [2018-12-17 09:37:12.129] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308] [Task.<anonymous>]
debug: The plugin [/Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-ghpages] was resolved indirectly
    → [2018-12-17 09:37:12.187] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/@bevry/pluginloader/source/index.js:173] [new PluginLoader]
debug: Loading plugin: /Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-ghpages
    → [2018-12-17 09:37:12.187] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308] [Task.<anonymous>]
debug: Loaded plugin: /Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-ghpages
    → [2018-12-17 09:37:12.189] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308] [Task.<anonymous>]
debug: load tasks ➞  load plugins > done
    → [2018-12-17 09:37:12.190] [events.js:272] [Object.onceWrapper]
notice: Set the exit code from unset to 1 because of error from: The action [load ready] failed to complete!
    → [2018-12-17 09:37:12.192] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:2711] [DocPad.error]
error: Error: The action [load ready] failed to complete!
    at docpadUtil.action.call.args (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:362:22)
    at TaskGroup.<anonymous> (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/util.js:377:11)
    at Object.onceWrapper (events.js:272:13)
    at TaskGroup.emit (events.js:180:13)
    at TaskGroup.emit (domain.js:422:20)
    at TaskGroup.listener (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at TaskGroup.emit (events.js:180:13)
    at TaskGroup.emit (domain.js:422:20)
    at TaskGroup.finish (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:272:13)
    at Task.emit (events.js:185:15)
    at Task.emit (domain.js:422:20)
    at Task.listener (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at Task.emit (events.js:180:13)
    at Task.emit (domain.js:422:20)
    at Task.finish (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:375:8)
    at TaskGroup.completeMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:507:5)
    at Object.onceWrapper (events.js:272:13)
    at TaskGroup.emit (events.js:180:13)
    at TaskGroup.emit (domain.js:440:23)
    at TaskGroup.listener (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at TaskGroup.emit (events.js:180:13)
    at TaskGroup.emit (domain.js:440:23)
    at TaskGroup.finish (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:272:13)
    at Task.emit (events.js:185:15)
    at Task.emit (domain.js:440:23)
    at Task.listener (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at Task.emit (events.js:180:13)
    at Task.emit (domain.js:440:23)
    at Task.finish (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:375:8)
    at completeMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:507:5)
    at TaskGroup.<anonymous> (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3298:16)
    at Object.onceWrapper (events.js:272:13)
    at TaskGroup.emit (events.js:180:13)
    at TaskGroup.emit (domain.js:440:23)
    at TaskGroup.listener (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at TaskGroup.emit (events.js:180:13)
    at TaskGroup.emit (domain.js:440:23)
    at TaskGroup.finish (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:272:13)
    at Task.emit (events.js:185:15)
    at Task.emit (domain.js:440:23)
    at Task.listener (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at Task.emit (events.js:180:13)
    at Task.emit (domain.js:440:23)
    at Task.finish (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:375:8)
    at completeMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:507:5)
    at next (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3337:9)
    at DocPad.loadPlugin (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3394:14)
    at Task.<anonymous> (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308:25)
    at ambi (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/ambi/source/index.js:77:3)
    at Domain.fireMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:323:14)
    at Task.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue [as _onImmediate] (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)

↳ Error: Plugin failed to instantiate: /Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-babel
    at DocPad.loadPlugin (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3389:15)
    at Task.<anonymous> (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308:25)
    at ambi (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/ambi/source/index.js:77:3)
    at Domain.fireMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:323:14)
    at Task.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue [as _onImmediate] (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)

↳ Error: Plugin [/Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-babel] failed to instantiate.
    at PluginLoader.create (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/@bevry/pluginloader/source/index.js:298:10)
    at DocPad.loadPlugin (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3386:51)
    at Task.<anonymous> (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308:25)
    at ambi (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/ambi/source/index.js:77:3)
    at Domain.fireMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:323:14)
    at Task.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue [as _onImmediate] (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)

↳ TypeError: Class constructor BasePlugin cannot be invoked without 'new'
    at new BabelPlugin (/Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-babel/out/babel.plugin.js:13:48)
    at PluginLoader.create (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/@bevry/pluginloader/source/index.js:287:19)
    at DocPad.loadPlugin (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3386:51)
    at Task.<anonymous> (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308:25)
    at ambi (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/ambi/source/index.js:77:3)
    at Domain.fireMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:323:14)
    at Task.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue [as _onImmediate] (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)

Please report it using this guide: https://docpad.org/bug-report
    → [2018-12-17 09:37:12.194] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:362] [docpadUtil.action.call.args]
debug: Emitting the event: notify
    → [2018-12-17 09:37:12.196] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:2624] [DocPad.notify]
critical: Error: A fatal error occured within DocPad
    at DocPad.fatal (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:2758:13)
    at /Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/cli.js:199:21
    at /Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:1296:18
    at docpadUtil.action.call.args (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:366:45)
    at TaskGroup.<anonymous> (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/util.js:377:11)
    at Object.onceWrapper (events.js:272:13)
    at TaskGroup.emit (events.js:180:13)
    at TaskGroup.emit (domain.js:422:20)
    at TaskGroup.listener (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at TaskGroup.emit (events.js:180:13)
    at TaskGroup.emit (domain.js:422:20)
    at TaskGroup.finish (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:272:13)
    at Task.emit (events.js:185:15)
    at Task.emit (domain.js:422:20)
    at Task.listener (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at Task.emit (events.js:180:13)
    at Task.emit (domain.js:422:20)
    at Task.finish (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:375:8)
    at TaskGroup.completeMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:507:5)
    at Object.onceWrapper (events.js:272:13)
    at TaskGroup.emit (events.js:180:13)
    at TaskGroup.emit (domain.js:440:23)
    at TaskGroup.listener (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at TaskGroup.emit (events.js:180:13)
    at TaskGroup.emit (domain.js:440:23)
    at TaskGroup.finish (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:272:13)
    at Task.emit (events.js:185:15)
    at Task.emit (domain.js:440:23)
    at Task.listener (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at Task.emit (events.js:180:13)
    at Task.emit (domain.js:440:23)
    at Task.finish (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:375:8)
    at completeMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:507:5)
    at TaskGroup.<anonymous> (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3298:16)
    at Object.onceWrapper (events.js:272:13)
    at TaskGroup.emit (events.js:180:13)
    at TaskGroup.emit (domain.js:440:23)
    at TaskGroup.listener (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at TaskGroup.emit (events.js:180:13)
    at TaskGroup.emit (domain.js:440:23)
    at TaskGroup.finish (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:272:13)
    at Task.emit (events.js:185:15)
    at Task.emit (domain.js:440:23)
    at Task.listener (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at Task.emit (events.js:180:13)
    at Task.emit (domain.js:440:23)
    at Task.finish (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:375:8)
    at completeMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:507:5)
    at next (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3337:9)
    at DocPad.loadPlugin (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3394:14)
    at Task.<anonymous> (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308:25)
    at ambi (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/ambi/source/index.js:77:3)
    at Domain.fireMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:323:14)
    at Task.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue [as _onImmediate] (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)

↳ Error: Plugin failed to instantiate: /Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-babel
    at DocPad.loadPlugin (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3389:15)
    at Task.<anonymous> (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308:25)
    at ambi (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/ambi/source/index.js:77:3)
    at Domain.fireMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:323:14)
    at Task.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue [as _onImmediate] (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)

↳ Error: Plugin [/Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-babel] failed to instantiate.
    at PluginLoader.create (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/@bevry/pluginloader/source/index.js:298:10)
    at DocPad.loadPlugin (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3386:51)
    at Task.<anonymous> (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308:25)
    at ambi (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/ambi/source/index.js:77:3)
    at Domain.fireMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:323:14)
    at Task.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue [as _onImmediate] (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)

↳ TypeError: Class constructor BasePlugin cannot be invoked without 'new'
    at new BabelPlugin (/Users/username/Documents/projects/client--clientname/semantic-ui/build-semantic/docs/node_modules/docpad-plugin-babel/out/babel.plugin.js:13:48)
    at PluginLoader.create (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/@bevry/pluginloader/source/index.js:287:19)
    at DocPad.loadPlugin (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3386:51)
    at Task.<anonymous> (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308:25)
    at ambi (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/ambi/source/index.js:77:3)
    at Domain.fireMethod (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:323:14)
    at Task.fire (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue [as _onImmediate] (/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)

Please report it using this guide: https://docpad.org/bug-report
    → [2018-12-17 09:37:12.200] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:2762] [DocPad.fatal]
debug: Emitting the event: notify
    → [2018-12-17 09:37:12.208] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:2624] [DocPad.notify]
info: DocPad is shutting down...
    → [2018-12-17 09:37:12.212] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:2766] [DocPad.fatal]
debug: action runner ➞  runner task for action: ready > done
    → [2018-12-17 09:37:12.213] [events.js:272] [Object.onceWrapper]
debug: Emitting the event: docpadDestroy
    → [2018-12-17 09:37:12.216] [/Users/username/.nvm/versions/node/v9.11.2/lib/node_modules/docpad/edition-esnext/lib/docpad.js:1337] [Immediate._onImmediate]
debug: Emitted the event: notify
    → [2018-12-17 09:37:12.217] [events.js:272] [Object.onceWrapper]
debug: Emitted the event: notify
    → [2018-12-17 09:37:12.217] [events.js:272] [Object.onceWrapper]
debug: Emitted the event: docpadDestroy
    → [2018-12-17 09:37:12.218] [events.js:272] [Object.onceWrapper]
Shutdown complete. See you next time.

```

thanks

**Comment by MartynCook** [comment]
Looks like this might be due to `coffee-script` v1 rename & update to `coffeescript` v2. 

**Docpad v6.79.0** seems to run. (I have a broken front end, but that could be this project ha)

**Comment by balupton** [comment]
Looking at the logs the DocPad Babel Plugin needs to be upgraded to CoffeeScript v2

**Comment by williammalo** [comment]
oh, I've been neglecting this gitbub account, lemme do that real quick

**Comment by balupton** [comment]
Closing in favour of https://github.com/docpad/docpad-plugin-babel/issues/9
