### ISSUE TITLE
Cannot get past "docpad init"

### ISSUE THREAD

**Issue by barbu110** [docpad/docpad#1097]
I am trying to run `docpad init` in an empty folder and here is the output:

```
➜  docs docpad init
info: Welcome to DocPad v6.82.5 (global installation: /home/victor/.nvm/versions/node/v10.15.3/lib/node_modules/docpad)
notice: Please donate to DocPad or have your company sponsor it: https://docpad.org/donate
info: Contribute: https://docpad.org/docs/contribute
info: Plugins: 
info: Environment: development
info: Updating the exchange... 
This can take a moment...
info: Updated the exchange
(node:135070) UnhandledPromiseRejectionWarning: Error: eachr does not know how to iterate what was passed to it
    at eachr (/home/victor/.nvm/versions/node/v10.15.3/lib/node_modules/docpad/node_modules/eachr/source/index.js:37:9)
    at /home/victor/.nvm/versions/node/v10.15.3/lib/node_modules/docpad/edition-esnext/lib/docpad.js:854:11
    at /home/victor/.nvm/versions/node/v10.15.3/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3481:16
    at /home/victor/.nvm/versions/node/v10.15.3/lib/node_modules/docpad/edition-esnext/lib/docpad.js:2008:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I have `npm` and `docpad` globally available on my system. Versions are:
 - Node `v10.15.3`
 - NPM `6.14.5`

What is the problem, please? Thanks!

**Comment by balupton** [comment]
The DocPad project is archived as no one wishes to pay for the significant maintenance burden. See the notice at https://docpad.bevry.me
