### ISSUE TITLE
Error with: docpad install serve

### ISSUE THREAD

**Issue by EloFran** [docpad/docpad#1124]
1. **docpad init**
2. **docpad install serve** return:
```
notice: Set the exit code from unset to 1 because of fatal from: A fatal error occured within DocPad       
critical: Error: A fatal error occured within DocPad
    at new Errlop (C:\Users\eloyf\AppData\Roaming\npm\node_modules\docpad\node_modules\errlop\edition-es5\index.js:61:18)
    at DocPad.fatal (C:\Users\eloyf\AppData\Roaming\npm\node_modules\docpad\edition-esnext\lib\docpad.js:2677:13)
    at process.emit (events.js:326:22)
    at process.EventEmitter.emit (domain.js:483:12)
    at process._fatalException (internal/process/execution.js:165:25)
↳ ReferenceError: input is not defined
    at CAC.<anonymous> (C:\Users\eloyf\AppData\Roaming\npm\node_modules\docpad\edition-esnext\lib\cli.js:107:15)
    at CAC.runMatchedCommand (C:\Users\eloyf\AppData\Roaming\npm\node_modules\docpad\node_modules\cac\dist\index.js:597:34)
    at CAC.parse (C:\Users\eloyf\AppData\Roaming\npm\node_modules\docpad\node_modules\cac\dist\index.js:526:12)
    at C:\Users\eloyf\AppData\Roaming\npm\node_modules\docpad\edition-esnext\lib\cli.js:157:18
    at TaskGroup.<anonymous> (C:\Users\eloyf\AppData\Roaming\npm\node_modules\docpad\edition-esnext\lib\docpad.js:1358:16)
    at Object.onceWrapper (events.js:421:26)
    at TaskGroup.emit (events.js:314:20)
    at TaskGroup.EventEmitter.emit (domain.js:506:15)
    at TaskGroup.listener (C:\Users\eloyf\AppData\Roaming\npm\node_modules\docpad\node_modules\taskgroup\source\interface.js:45:10)
    at TaskGroup.emit (events.js:314:20)
Please report it using this guide: https://docpad.bevry.me/bug
```

**Comment by balupton** [comment]
Thanks, I'll look into it next week

**Comment by balupton** [comment]
@EloFran which DocPad version are you using, and can you upload somewhere the generated log file when using the `--debug` flag.

**Comment by balupton** [comment]
nvm, I suspect I know what the issue is: https://github.com/docpad/docpad/blob/master/source/lib/cli.coffee#L104-L106

will have a fix out this week or next

**Comment by balupton** [comment]
Still in the roadworks. Had a long delay to sort out travis ci making open-source paid, so had to move everything to github actions.

**Comment by balupton** [comment]
Still wrestling with the port from Travis CI to GitHub Actions - streaming the progress on Twitch https://twitch.tv/balupton - as there is a large backlog of items, if you wish for this to be a priority [then please sponsor](https://github.com/sponsors/balupton), otherwise I have other issues that I need to focus my limited unpaid time on.

**Comment by RichardBray** [comment]
This issue still seems to exist for me. Does anyone know if any progress has been made on it?

**Comment by balupton** [comment]
No progress has been made, however the fix should just be to change `action(->` in the lines before to `action((input) ->`

**Comment by RichardBray** [comment]
> No progress has been made, however the fix should just be to change `action(->` in the lines before to `action((input) ->`

Nice, this works 👍

**Comment by holiveira79** [comment]
> No progress has been made, however the fix should just be to change `action(->` in the lines before to `action((input) ->`

I also have this issue.
Tried editing the file cli.coffee and applying the fix and nothing seemed to change.
Can you please help a bit more?
