### ISSUE TITLE
npm install docpad-plugin-minicms not installing

### ISSUE THREAD

**Issue by s2zaman** [docpad/docpad#647]
My previous issue #646 was resolved by @balupton .
But this came up.
The error results from the command `npm install docpad-plugin-minicms`

```
...
npm http GET https://registry.npmjs.org/minimatch/-/minimatch-0.2.12.tgz
npm http 200 https://registry.npmjs.org/cssom/-/cssom-0.2.5.tgz
npm http 200 https://registry.npmjs.org/bufferjs/-/bufferjs-2.0.0.tgz
npm http 200 https://registry.npmjs.org/minimatch/-/minimatch-0.2.12.tgz

> unicode@0.4.4 postinstall C:\Users\VCR1\node_modules\docpad-plugin-minicms\nod
e_modules\slug\node_modules\unicode
> node install.js

try to read file /usr/share/unicode/UnicodeData.txt …
Warning: using slow naiv Buffer.indexOf function!
`npm install buffertools` to speed things up.
/usr/share/unicode/UnicodeData.txt not found.
try to read file /usr/share/unicode-data/UnicodeData.txt …
/usr/share/unicode-data/UnicodeData.txt not found.
try to download …
GET unicode.org:80/Public/UNIDATA/UnicodeData.txt
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 200 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/sigmund/-/sigmund-1.0.0.tgz
npm http 200 https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/lru-cache/-/lru-cache-2.3.1.tgz
npm http 200 https://registry.npmjs.org/sigmund/-/sigmund-1.0.0.tgz
npm http 200 https://registry.npmjs.org/lru-cache/-/lru-cache-2.3.1.tgz

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by rjmadhu** [comment]
unicodedatafile = {
    host: "unicode.org",

By this code :

unicodedatafile = {
    host: "http://unicode.org",
