### ISSUE TITLE
Docpad Project Boostrap Coffeekup Setup Error

### ISSUE THREAD

**Issue by oleersoy** [docpad/docpad#666]
When selecting the bootstrap project with coffeekup I get the following:

```
warning: Your project's local DocPad version is 6.50.0 instead of 6.50.1, you may experience problems. Run `docpad update` to fix this.
info: DocPad listening to http://localhost:9778/ on directory /home/ole/Documentation/tocgen/out
info: LiveReload listening to new socket on channel /docpad-livereload
info: Generating...
info: Generated 21/21 files in 2.481 seconds
info: Watching setup starting...

Error: Cannot find module 'watchr'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at DocPad.watchdir (/home/ole/Documentation/tocgen/node_modules/docpad/out/lib/docpad.js:1162:12)
    at Task.method (/home/ole/Documentation/tocgen/node_modules/docpad/out/lib/docpad.js:3308:23)
    at ambi (/home/ole/Documentation/tocgen/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:22:16)
    at /home/ole/Documentation/tocgen/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:123:21
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at Task.fire (/home/ole/Documentation/tocgen/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:120:21)
    at process._tickDomainCallback (node.js:459:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write after end
    at writeAfterEnd (/home/ole/.nvm/v0.10.15/lib/node_modules/docpad/node_modules/caterpillar/node_modules/readable-stream/lib/_stream_writable.js:130:12)
    at Logger.Writable.write (/home/ole/.nvm/v0.10.15/lib/node_modules/docpad/node_modules/caterpillar/node_modules/readable-stream/lib/_stream_writable.js:178:5)
    at Logger.log (/home/ole/.nvm/v0.10.15/lib/node_modules/docpad/node_modules/caterpillar/out/lib/caterpillar.js:190:10)
    at DocPad.log (/home/ole/.nvm/v0.10.15/lib/node_modules/docpad/out/lib/docpad.js:1936:16)
    at DocPad.log (/home/ole/.nvm/v0.10.15/lib/node_modules/docpad/out/lib/docpad.js:4:59)
    at forward (/home/ole/.nvm/v0.10.15/lib/node_modules/docpad/out/lib/docpad.js:3002:14)
    at /home/ole/.nvm/v0.10.15/lib/node_modules/docpad/out/lib/docpad.js:3017:17
    at /home/ole/.nvm/v0.10.15/lib/node_modules/docpad/out/lib/util.js:28:18
    at TaskGroup.<anonymous> (/home/ole/.nvm/v0.10.15/lib/node_modules/docpad/node_modules/safeps/out/lib/safeps.js:106:45)
    at TaskGroup.g (events.js:175:14)
    at TaskGroup.EventEmitter.emit (events.js:98:17)
    at TaskGroup.complete (/home/ole/.nvm/v0.10.15/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:389:12)
    at TaskGroup.itemCompletionCallback (/home/ole/.nvm/v0.10.15/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:247:15)
    at TaskGroup.EventEmitter.emit (events.js:98:17)
    at Task.<anonymous> (/home/ole/.nvm/v0.10.15/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:274:24)
    at Task.EventEmitter.emit (events.js:117:20)
    at Task.completionCallback (/home/ole/.nvm/v0.10.15/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:88:17)
    at ChildProcess.<anonymous> (/home/ole/.nvm/v0.10.15/lib/node_modules/docpad/node_modules/safeps/out/lib/safeps.js:156:20)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Process.ChildProcess._handle.onexit (child_process.js:802:5)

If I try to update docpad I get this:

ole@tungsten:~/Documentation/tocgen$ docpad update

module.js:340
    throw err;
          ^
Error: Cannot find module 'lazy-require'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ole/Documentation/tocgen/node_modules/docpad/out/lib/docpad.js:11:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
An error occured within the child DocPad instance: exited with a non-zero status code
ole@tungsten:~/Documentation/tocgen$ docpad install watchr

module.js:340
    throw err;
          ^
Error: Cannot find module 'lazy-require'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ole/Documentation/tocgen/node_modules/docpad/out/lib/docpad.js:11:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
An error occured within the child DocPad instance: exited with a non-zero status code
ole@tungsten:~/Documentation/tocgen$ docpad update

module.js:340
    throw err;
          ^
Error: Cannot find module 'lazy-require'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ole/Documentation/tocgen/node_modules/docpad/out/lib/docpad.js:11:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
An error occured within the child DocPad instance: exited with a non-zero status code
```

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
