### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by Zearin** [docpad/docpad#711]
Here’s a direct copy-paste (my username redacted) of my latest terminal output:

```bash
 docpad generate --env static
info: Welcome to DocPad v6.54.6 (local installation: /usr/local/lib/node_modules/docpad)
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: coffeescript, eco, ghpages, livereload, marked, partials, stylus, text
info: Environment: static
info: Generating...
error: Something went wrong with the action
error: An error occured: 
TypeError: Cannot read property 'encoding' of null
    at /usr/local/lib/node_modules/docpad/out/lib/models/document.js:117:28
    at DocumentModel.FileModel.parse (/usr/local/lib/node_modules/docpad/out/lib/models/file.js:556:7)
    at DocumentModel.parse (/usr/local/lib/node_modules/docpad/out/lib/models/document.js:75:37)
    at TaskGroup.<anonymous> (/usr/local/lib/node_modules/docpad/out/lib/models/file.js:439:21)
    at TaskGroup.g (events.js:175:14)
    at TaskGroup.EventEmitter.emit (events.js:98:17)
    at TaskGroup.complete (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:546:14)
    at TaskGroup.itemCompletionCallback (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:346:17)
    at TaskGroup.EventEmitter.emit (events.js:95:17)
    at Task.<anonymous> (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:401:26)
    at Task.EventEmitter.emit (events.js:117:20)
    at Task.completionCallback (/usr/local/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:129:19)
    at /usr/local/lib/node_modules/docpad/out/lib/models/file.js:473:20
    at /usr/local/lib/node_modules/docpad/node_modules/safefs/out/lib/safefs.js:78:18
    at fs.js:266:14
    at /Users/my-user-name/Developer/Projects/GitHub/umd-arachne.github.io/node_modules/docpad-plugin-ghpages/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:103:5
    at Object.oncomplete (fs.js:107:15)
info: Shutting down... cya next time!
```

That tells me **absolutely nothing** about where to look for the problem.  

It *does* say that there is an encoding error somewhere (`TypeError: Cannot read property 'encoding' of null`).  

**But, which file?**  Can’t DocPad at least tell me the filename where the error occurred?  

«grumble…»

I don’t want help fixing this particular error.  I want DocPad’s error reporting to be helpful so that it’s easy for users to fix their own problems.

**Comment by balupton** [comment]
Recent versions of DocPad now support a `context` string property on error objects where you can write about what caused the error.
