### ISSUE TITLE
TypeError: Cannot call method 'isDirectory' of null

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#792]
Just checked mixpanel after a few months, and noticed that this error has been getting incurred THOUSANDS of times a day by people... Ever since watchr v2.4.7 December 19, 2013.

```
DocPad v6.61.0
Node v0.10.21
Platform: win32

Stack:
TypeError: Cannot call method 'isDirectory' of null
  at _Class.changeHandler (d:\Documents\GitHub\docpad-simpleblog\node_modules\docpad\out\lib\docpad.js:3579:61)
  at _Class.EventEmitter.emit (events.js:106:17)
  at _Class.bubble (d:\Documents\GitHub\docpad-simpleblog\node_modules\docpad\node_modules\watchr\out\lib\watchr.js:177:19)
  at _Class.bubble (d:\Documents\GitHub\docpad-simpleblog\node_modules\docpad\node_modules\watchr\out\lib\watchr.js:4:61)
  at _Class.watchr.children.(anonymous function).watch.listeners.change (d:\Documents\GitHub\docpad-simpleblog\node_modules\docpad\node_modules\watchr\out\lib\watchr.js:488:36)
  at _Class.EventEmitter.emit (events.js:106:17)
  at watchr.watchChild.next (d:\Documents\GitHub\docpad-simpleblog\node_modules\docpad\node_modules\watchr\out\lib\watchr.js:389:26)
  at createWatcher (d:\Documents\GitHub\docpad-simpleblog\node_modules\docpad\node_modules\watchr\out\lib\watchr.js:677:9)
  at watch (d:\Documents\GitHub\docpad-simpleblog\node_modules\docpad\node_modules\watchr\out\lib\watchr.js:739:16)
  at _Class.watchChild (d:\Documents\GitHub\docpad-simpleblog\node_modules\docpad\node_modules\watchr\out\lib\watchr.js:476:46)
  at Task. (d:\Documents\GitHub\docpad-simpleblog\node_modules\docpad\node_modules\watchr\out\lib\watchr.js:382:29)
  at ambi (d:\Documents\GitHub\docpad-simpleblog\node_modules\docpad\node_modules\ambi\out\lib\ambi.js:23:18)
  at fire (d:\Documents\GitHub\docpad-simpleblog\node_modules\docpad\node_modules\taskgroup\out\lib\taskgroup.js:159:23)
  at b (domain.js:183:18)
  at Domain.run (domain.js:123:23)
  at Task.fire (d:\Documents\GitHub\docpad-simpleblog\node_modules\docpad\node_modules\taskgroup\out\lib\taskgroup.js:166:25)
  at processImmediate [as _immediateCallback] (timers.js:330:15)
```

Now we could just do a undefined check and skip that section of code, but the problem that particular line:

```
isDirectory = (fileCurrentStat or filePreviousStat).isDirectory()
```

Should always work, as at least one of those stats should be defined. This need to be looked into.

**Comment by balupton** [comment]
This should be fixed from watchr v2.4.12 December 17, 2014 and above.

Closing unless someone reports it again.
