### ISSUE TITLE
Unable of giving my first step with docpad.

### ISSUE THREAD

**Issue by lifeBalance** [docpad/docpad#826]
Hi, I was following the beginners tutorial, but when I'm trying to `docpad run` I get the following error:

```
$ docpad run
info: Welcome to DocPad v6.64.0 (local installation: /Users/javi/Sites/docpad/node_modules/docpad)
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: eco, livereload, marked
info: Environment: development
info: DocPad listening to http://0.0.0.0:9778/ on directory /Users/javi/Sites/docpad/out
info: LiveReload listening to new socket on channel /docpad-livereload
info: Generating...
warning: Something went wrong while rendering: default.html.eco
Object #<Object> has no method 'getPreparedTitle'
warning: Something went wrong while rendering: about.html
Object #<Object> has no method 'getPreparedTitle'
error: Something went wrong with the action
error: An error occured:
TypeError: Object #<Object> has no method 'getPreparedTitle'
  at Object.eval (<anonymous>:45:34)
  at Object.eval (<anonymous>:83:8)
  at eval (<anonymous>:85:6)
  at Function.eco.render (/Users/javi/Sites/docpad/node_modules/docpad-plugin-eco/node_modules/eco/lib/index.js:26:25)
  at EcoPlugin.render (/Users/javi/Sites/docpad/node_modules/docpad-plugin-eco/out/eco.plugin.js:24:32)
  at ambi (/Users/javi/Sites/docpad/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:25:27)
  at Task.<anonymous> (/Users/javi/Sites/docpad/node_modules/docpad/node_modules/event-emitter-grouped/out/lib/event-emitter-grouped.js:45:23)
  at ambi (/Users/javi/Sites/docpad/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:23:18)
  at fire (/Users/javi/Sites/docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:163:25)
  at b (domain.js:183:18)
  at Domain.run (domain.js:123:23)
  at Task.fire (/Users/javi/Sites/docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:173:25)
  at processImmediate [as _immediateCallback] (timers.js:330:15)

warning: Something went wrong while rendering: default.html.eco
Object #<Object> has no method 'getPreparedTitle'
warning: Something went wrong while rendering: index.html
Object #<Object> has no method 'getPreparedTitle'
info: Shutting down... cya next time!
```

I feel the documentation is a bit short.

**Comment by balupton** [comment]
Try again with v6.80
