### ISSUE TITLE
File watcher issue

### ISSUE THREAD

**Issue by zenorocha** [docpad/docpad#868]
> What you did?

Ran `docpad run`.

> What happened

```
info: Generated 436/443 files in 46.506 seconds
info: Watching setup starting...
error: Something went wrong with the action
error: An error occured:
Error: The task [server tasks ➞  start the server] just completed, but it had already completed earlier, this is unexpected. State information is:
{ error: { [Error: accept EMFILE] code: 'EMFILE', errno: 'EMFILE', syscall: 'accept' },
  previousResult: [],
  currentArguments: [ { [Error: accept EMFILE] code: 'EMFILE', errno: 'EMFILE', syscall: 'accept' } ] }
  at Task.exit (/Users/zeno/Projects/alloyui.com-master/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:281:15)
  at Server.<anonymous> (/Users/zeno/Projects/alloyui.com-master/node_modules/docpad/out/lib/docpad.js:4372:18)
  at Server.g (events.js:175:14)
  at Server.EventEmitter.emit (events.js:95:17)
  at TCP.onconnection (net.js:1159:10)
error: To report the above error, follow the guide at: http://docpad.org/bug-report
```

> What you expected

For my files to be rendered and watched.

```
$ docpad --version
v6.69.0

$ npm --version
1.3.11

$ node --version
v0.10.21
```

Mac OS X v10.9

Repository: https://github.com/liferay/alloyui.com

**Comment by balupton** [comment]
Does this still happen?

If so, can you forward the error to: http://github.com/bevry/watchr

Thanks!

**Comment by zenorocha** [comment]
It doesn't, thanks!
