### ISSUE TITLE
docpad run gives TypeError: Object #<Object> has no method 'bind' at Task.<anonymous>

### ISSUE THREAD

**Issue by simonsmithies** [docpad/docpad#875]
docpad --version:  v6.69.0
node --version:  v0.10.30
npm --version: 2.0.0-alpha-5
Plugins: cleanurls, coffeescript, downloader, eco, less, livereload, marked, partials, related, stylus, text
Environment: development
Mac OS X v10.9.4 mavericks, Intel core i3

I'm new to Node and Docpad.

Installed Node, NPM and Docpad. Am 50% of the way through converting a site from a CMS, with no problems, at least that I've noticed (in fact I think docpad's brilliant at this point).

Spent some time trying to get contactify and formmail going. Gave up, think my problems there relate to unresolved issues with those plugins in my late versions of node and docpad. And I /think/ I've fully uninstalled both these plugins (npm uninstall --save docpad-plugin-xx).

Am now noticing the below error on startup. Note that Docpad seems to run OK, so it's possible the error may have been happening prior to the plugin problems and I didn't notice.

```
TypeError: Object # has no method 'bind'
at Task. (~/Dropbox/docpad/dd-bootstrap/node_modules/docpad/out/lib/docpad.js:1723:27)
at ambi (~/Dropbox/docpad/dd-bootstrap/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:55:18)
at fire (~/Dropbox/docpad/dd-bootstrap/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:384:27)
at b (domain.js:183:18)
at Domain.run (domain.js:123:23)
at Task.fire (~/Dropbox/docpad/dd-bootstrap/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:398:25)
at Object._onImmediate (~/Dropbox/docpad/dd-bootstrap/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:414:26)
at processImmediate as _immediateCallback
```

**Comment by balupton** [comment]
Added better error reporting for this in v6.77.1.
