### ISSUE TITLE
Unkown meta parser c

### ISSUE THREAD

**Issue by marfalkov** [docpad/docpad#879]
DocPad v6.69.0

DocPad doesn't throw the following error when I add a comment to the top of the minified javascript.
The file was minified with the latest google closure compiler.

```
Error: Unknown meta parser c on fakepath/front-min.js
  at fakepath/node_modules/docpad/out/lib/models/document.js:111:25
  at DocumentModel.FileModel.parse (fakepath//node_modules/docpad/out/lib/models/file.js:622:7)
  at DocumentModel.parse (fakepath/node_modules/docpad/out/lib/models/document.js:76:37)
  at Task.<anonymous> (fakepath/node_modules/docpad/out/lib/models/file.js:561:21)
  at ambi (fakepath/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:55:18)
  at fire (fakepath/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:384:27)
  at b (domain.js:183:18)
  at Domain.run (domain.js:123:23)
  at Task.fire (fakepath/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:398:25)
  at Object._onImmediate (fakepath/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:414:26)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
error: To report the above error, follow the guide at: http://docpad.org/bug-report
```

**Comment by balupton** [comment]
Can't seem to find the email.
