### ISSUE TITLE
Docpad Run + Twitter Bootstrap = npm ERR! Darwin 13.4.0

### ISSUE THREAD

**Issue by spencerthayer** [docpad/docpad#894]
Full command log below:

```
$ docpad run
info: Welcome to DocPad v6.69.1 (global installation: /usr/local/lib/node_modules/docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: 
info: Environment: development
info: Updating the exchange... 
This can take a moment...
info: Updated the exchange
info: You are about to create your new project inside your current directory. Below is a list of skeletons to bootstrap your new project:

  1.    HTML5 Boilerplate
    HTML5 Boilerplate skeleton for DocPad. Bare essentials for building a modern website with best practices

  2.    HTML5 Boilerplate with Grunt
    The HTML5 Boilerplate skeleton with Grunt for concatenation and minification of assets

  3.    HTML5 Boilerplate with Jade and LESS
    A skeleton that uses the HTML5 boilerplate with Jade and LESS. Also includes jQuery and the livereload plugin.

  4.    Twitter Bootstrap
    Simple and flexible HTML, CSS, and Javascript for popular user interface components and interactions

  5.    Twitter Bootstrap with Jade
    Twitter Bootstrap skeleton for DocPad developed using Jade (a HAML alternative for Node.js)

  6.    Twitter Bootstrap with Coffeekup
    Twitter Bootstrap skeleton for DocPad developed using Coffeekup (markup as coffeescript)

  7.    Kitchensink
    A DocPad Skeleton useful for showcasing different features and functionality of DocPad. Implemented using Twitter Bootstrap

  8.    Benjamin Lupton's Website
    Use Benjamin Lupton's website - http://balupton.com - as the base for your own :)

  9.    DocPad's Website
    DocPad's Website

  10.   Bevry's Website
    Bevry's Website (the company behind DocPad)

  11.   Startup Hostel's Website
    Startup Hostel, the home in paradise for the doers of the world!

  12.   NodeChat
    Node Chat, built using Socket.io, DocPad, Backbone.js and Twitter Bootstrap

  13.   SlidePad
    Create HTML5 Presentations easily with DocPad

  14.   Reveal.js
    Create Reveal.js presentations easily with DocPad

  15.   Conference Boilerplate
    A kickstart to create websites for conference/events

  16.   Zurb Foundation(SASS)
    A minimal Zurb Foundation skeleton with SASS and coffeescript

  17.   Meny
    Create a simple page utilizing the Meny 3D menu

  18.   YUI PureCSS
    YUI PureCSS skeleton for DocPad

  19.   Zurb Foundation
    A clean responsive template that contains a logical setup for a website + blog

  20.   Casteasoft Foundation Simple Blog
    This skeleton supports blog posts, clean url, posts url using date-url based, pagination on blog posts listing, and more.

  21.   No Skeleton
    Prefer to start from scratch? You can get started without any skeleton if you wish

Which skeleton will you use? [1-21]
  1.    HTML5 Boilerplate
  2.    HTML5 Boilerplate with Grunt
  3.    HTML5 Boilerplate with Jade and LESS
  4.    Twitter Bootstrap
  5.    Twitter Bootstrap with Jade
  6.    Twitter Bootstrap with Coffeekup
  7.    Kitchensink
  8.    Benjamin Lupton's Website
  9.    DocPad's Website
  10.   Bevry's Website
  11.   Startup Hostel's Website
  12.   NodeChat
  13.   SlidePad
  14.   Reveal.js
  15.   Conference Boilerplate
  16.   Zurb Foundation(SASS)
  17.   Meny
  18.   YUI PureCSS
  19.   Zurb Foundation
  20.   Casteasoft Foundation Simple Blog
  21.   No Skeleton
> 4
info: Installing the Twitter Bootstrap skeleton into /Users/spencerthayer/Desktop/chicoryio 
This can take a moment...
Initialized empty Git repository in /Users/spencerthayer/Desktop/chicoryio/.git/
From https://github.com/docpad/twitter-bootstrap.docpad
 * [new branch]      docpad-6.x -> skeleton/docpad-6.x
 * [new branch]      master     -> skeleton/master
From https://github.com/docpad/twitter-bootstrap.docpad
 * branch            docpad-6.x -> FETCH_HEAD
info: npm install

> taskgroup@3.3.9 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-partials/node_modules/taskgroup
> node ./cyclic.js


> safefs@3.1.1 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-cleanurls/node_modules/safefs
> node ./cyclic.js


> taskgroup@3.3.9 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-cleanurls/node_modules/taskgroup
> node ./cyclic.js


> typechecker@2.0.8 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-partials/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js


> ambi@2.1.6 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-partials/node_modules/taskgroup/node_modules/ambi
> node ./cyclic.js


> ambi@2.1.6 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-cleanurls/node_modules/taskgroup/node_modules/ambi
> node ./cyclic.js


> taskgroup@3.3.9 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-downloader/node_modules/taskgroup
> node ./cyclic.js


> typechecker@2.0.8 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-partials/node_modules/taskgroup/node_modules/ambi/node_modules/typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-cleanurls/node_modules/taskgroup/node_modules/ambi/node_modules/typechecker
> node ./cyclic.js


> ambi@2.1.6 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-downloader/node_modules/taskgroup/node_modules/ambi
> node ./cyclic.js


> safefs@3.1.1 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad/node_modules/safefs
> node ./cyclic.js


> taskgroup@3.3.9 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-text/node_modules/taskgroup
> node ./cyclic.js


> taskgroup@3.3.9 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad/node_modules/taskgroup
> node ./cyclic.js


> safeps@2.2.12 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad/node_modules/safeps
> node ./cyclic.js


> ambi@2.1.6 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad/node_modules/ambi
> node ./cyclic.js


> typechecker@2.0.8 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad/node_modules/typechecker
> node ./cyclic.js


> cson@1.4.5 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad/node_modules/cson
> node ./cyclic.js


> typechecker@2.0.8 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-livereload/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-downloader/node_modules/taskgroup/node_modules/ambi/node_modules/typechecker
> node ./cyclic.js


> ambi@2.1.6 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-text/node_modules/taskgroup/node_modules/ambi
> node ./cyclic.js


> safefs@3.0.6 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad/node_modules/istextorbinary/node_modules/safefs
> node ./cyclic.js


> taskgroup@3.4.0 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad/node_modules/safeps/node_modules/taskgroup
> node ./cyclic.js


> ambi@2.1.6 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-text/node_modules/bal-util/node_modules/ambi
> node ./cyclic.js


> typechecker@2.0.8 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-text/node_modules/bal-util/node_modules/typechecker
> node ./cyclic.js


> safefs@3.0.6 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-text/node_modules/bal-util/node_modules/safefs
> node ./cyclic.js


> typechecker@2.0.8 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-text/node_modules/taskgroup/node_modules/ambi/node_modules/typechecker
> node ./cyclic.js


> ambi@2.2.0 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad/node_modules/safeps/node_modules/taskgroup/node_modules/ambi
> node ./cyclic.js


> ws@0.4.32 install /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad-plugin-livereload/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN deprecated extendable@0.0.6: This project has been renamed to extendible. This project will not receive any updates anymore

> js2coffee@0.2.7 preinstall /Users/spencerthayer/Desktop/chicoryio/node_modules/docpad/node_modules/cson/node_modules/js2coffee
> npm run-script ./cyclic.js

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.7
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: eco@'>=1.1.0 <1.2.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0","1.0.1","1.0.2","1.0.3","1.1.0-rc-1","1.1.0-rc-2","1.1.0-rc-3"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/spencerthayer/Desktop/chicoryio/npm-debug.log
error: Something went wrong with the action
error: An error occured: 
Error: npm WARN deprecated extendable@0.0.6: This project has been renamed to extendible. This project will not receive any updates anymore
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.7
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: eco@'>=1.1.0 <1.2.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0","1.0.1","1.0.2","1.0.3","1.1.0-rc-1","1.1.0-rc-2","1.1.0-rc-3"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/spencerthayer/Desktop/chicoryio/npm-debug.log

  at ChildProcess.<anonymous> (/usr/local/lib/node_modules/docpad/node_modules/safeps/out/lib/safeps.js:165:23)
  at ChildProcess.emit (events.js:98:17)
  at maybeClose (child_process.js:756:16)
  at Process.ChildProcess._handle.onexit (child_process.js:823:5)
error: To report the above error, follow the guide at: http://docpad.org/bug-report
info: Shutting down... cya next time!
```

**Comment by garthk** [comment]
This is a terrible out-of-the-box experience:

* docpad tells you to use a skeleton
* you choose one
* it breaks
* you spend time tracking down the problem
* you end up here, and discover they're known-broken

Please, strip the skeletons out if the team and community can't or won't maintain them.

**Comment by spencerthayer** [comment]
@garthk  +1

**Comment by balupton** [comment]
@garthk is you find a broken skeleton, send a pull request on https://github.com/docpad/extras/blob/docpad-6.x/exchange.json to add `(out of date)` to it's name.

**Comment by austinbutler** [comment]
Should any distinction be made between outdated but working and outdated, fully not working skeletons?

I agree this is a pretty bad experience, since after working through npm permissions issues I finally get to the point of trying to get a site started and I choose a skeleton that fails during rendering. Since I already had issues I start thinking it's my fault, maybe I installed Docpad wrong.

On the other hand I do think it's useful, so maybe cut down on the amount of skeletons available and keep a few as officially maintained that are presented to the user during install?

For reference, I tried three and one worked. If I get an answer to my first question I can put in a pull request for these.

5. Twitter Bootstrap with Jade - Does run, has errors
17. Zurb Foundation(SASS) - Does not run
20. Zurb Foundation - Does not run

**Comment by barbalex** [comment]
Let me tell you my impressions of docpad:

1. looks nice, could use it for a project
2. I like that it uses JavaScript which I know well
3. extensive use of coffee script, eco and some coffee script based html language - uups. Seems like my JavaScript knowledge will not help me as much as I hoped
4. lets try: install, then `docpad run`
5. there is a bootstrap skeleton - whoa. Use it!
6. Hm. Lot's of errors during installation. But look, it works
7. VERY nice how the skeleton helps me build nifty features
8. Love how I am moving ahead thanks to this nice tool
9. Issues #1025  #1026: I am completely blocked. Should I have used Jekyll after all?
10. After lots of digging and finding this issue: Maybe I should begin again at zero without using a skeleton. Is it worth it?

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80.
