### ISSUE TITLE
Error: Cannot find module 'getrepos' with balupton sceleton

### ISSUE THREAD

**Issue by ischurov** [docpad/docpad#895]
I'm trying to begin with https://github.com/balupton/website

So the following lines are OK:
```
git clone git://github.com/balupton/balupton.docpad.git
cd balupton.docpad
npm install
```
Then I do

```docpad run```

And get

```
[user@maccie balupton.docpad #2395]$ docpad run                                  ~/prj/ilya.schurov.com/balupton.docpad
info: Welcome to DocPad v6.69.1 (local installation: /Users/user/prj/ilya.schurov.com/balupton.docpad/node_modules/docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: cachr, cleanurls, coffeekup, coffeescript, eco, feedr, livereload, marked, partials, services, stylus, text
info: Environment: development
info: DocPad listening to http://0.0.0.0:9778/ on directory /Users/user/prj/ilya.schurov.com/balupton.docpad/out
info: LiveReload listening to new socket on channel /docpad-livereload
info: Generating...
info: Fetching your latest projects for display within the website
error: Something went wrong with the action
error: An error occured:
Error: Cannot find module 'getrepos'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.module.exports.events.generateBefore (/Users/user/prj/ilya.schurov.com/balupton.docpad/docpad.coffee:351:19)
  at ambi (/Users/user/prj/ilya.schurov.com/balupton.docpad/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:55:18)
  at DocPad.<anonymous> (/Users/user/prj/ilya.schurov.com/balupton.docpad/node_modules/docpad/out/lib/docpad.js:971:25)
  at ambi (/Users/user/prj/ilya.schurov.com/balupton.docpad/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:55:18)
  at Task.<anonymous> (/Users/user/prj/ilya.schurov.com/balupton.docpad/node_modules/docpad/node_modules/event-emitter-grouped/out/lib/event-emitter-grouped.js:45:23)
  at ambi (/Users/user/prj/ilya.schurov.com/balupton.docpad/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:55:18)
  at fire (/Users/user/prj/ilya.schurov.com/balupton.docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:384:27)
  at b (domain.js:183:18)
  at Domain.run (domain.js:123:23)
  at Task.fire (/Users/user/prj/ilya.schurov.com/balupton.docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:398:25)
  at Object._onImmediate (/Users/user/prj/ilya.schurov.com/balupton.docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:414:26)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
error: To report the above error, follow the guide at: http://docpad.org/bug-report
info: Shutting down... cya next time!
```
System info:

```
[user@maccie balupton.docpad #2399]$ docpad --version                            ~/prj/ilya.schurov.com/balupton.docpad
v6.69.1 (local installation: /Users/user/prj/ilya.schurov.com/balupton.docpad/node_modules/docpad)
[user@maccie balupton.docpad #2400]$ node --version                              ~/prj/ilya.schurov.com/balupton.docpad
v0.10.33
[user@maccie balupton.docpad #2401]$ npm --version                               ~/prj/ilya.schurov.com/balupton.docpad
2.1.8
[user@maccie balupton.docpad #2402]$ uname -a                                    ~/prj/ilya.schurov.com/balupton.docpad
Darwin maccie 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,1 Darwin
```
OS: Mac OS X Yosemite.

Running `docpad` with `-d` gives a little bit more info:

```
...
info: Fetching your latest projects for display within the website
    → [2014-11-17 02:59:22.021] [/Users/user/prj/ilya.schurov.com/balupton.docpad/docpad.coffee:361] [module.exports.events.generateBefore]
error: Something went wrong with the action
    → [2014-11-17 02:59:22.027] [/Users/user/prj/ilya.schurov.com/balupton.docpad/node_modules/docpad/out/lib/interfaces/console.js:107] [ConsoleInterface.destroyWithError]
error: An error occured:
Error: Cannot find module 'getrepos'
    at Module._resolveFilename (module.js:338:15)
...
```

**Comment by balupton** [comment]
Never experienced this, but I've been doing a lot of work on that skeleton so should be fine. Happy to re-open if still an issue.
