### ISSUE TITLE
node 0.11.x compatibility

### ISSUE THREAD

**Issue by me6iaton** [docpad/docpad#902]
I can only use 0.11.x node for my project, here are my haks for this.

coffeescript compatibility bag:
```js
error: undefined '/home/me6iaton/Dropbox/.docpad.cson'
error: null
error: null 
TypeError: undefined is not a function
  at Object.exports.eval (/var/www/Docpad/docpad-skeleton-bootstrap-jade/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/coffee-script.js:133:47)
  at CSON.parseSync (/var/www/Docpad/docpad-skeleton-bootstrap-jade/node_modules/docpad/node_modules/cson/out/lib/cson.js:105:34)
  at ambi (/var/www/Docpad/docpad-skeleton-bootstrap-jade/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:57:27)
  at [object Object]._onTimeout (/var/www/Docpad/docpad-skeleton-bootstrap-jade/node_modules/docpad/node_modules/cson/out/lib/cson.js:89:18)
  at Timer.listOnTimeout (timers.js:133:15)
error: null
info: null
```
hack:
https://github.com/me6iaton/coffeescript/commit/6c7fdb407705e68690758a06547da3f986e31b9c

Error: Could not find the layout default 
hack:
fix fileFullPath bag, the first letter in fileFullPath lowercase 
https://github.com/me6iaton/docpad/commit/291edfe88f1324a0ae86af5741114ebd8ea98dfa

**Comment by theqwertman** [comment]
me6iaton, could you do a pull request for your fix?

**Comment by me6iaton** [comment]
It's too dirty hack for this, I modified https://github.com/me6iaton/coffeescript/commit/6c7fdb407705e68690758a06547da3f986e31b9c but that's another repo

**Comment by balupton** [comment]
0.12 and iojs support is in v6.70
