### ISSUE TITLE
docpad run failing

### ISSUE THREAD

**Issue by ezmiller** [docpad/docpad#920]
I just ran the following commands and got an error:

```
npm install -g docpad@6.70
mkdir my-new-project
cd my-new-project
docpad run
```

The error looked like: 
```
nfo: Welcome to DocPad v6.70.1 (global installation: /usr/local/lib/node_modules/docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins:
info: Environment: development
info: Updating the exchange...
This can take a moment...
error: Something went wrong with the action
error: An error occured:
TypeError: undefined is not a function
  at /usr/local/lib/node_modules/docpad/out/lib/docpad.js:1571:23
  at Request.callback (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/index.js:746:30)
  at Request.<anonymous> (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/index.js:135:10)
  at Request.emit (events.js:107:17)
  at Stream.<anonymous> (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/index.js:938:12)
  at Stream.emit (events.js:129:20)
  at Unzip.<anonymous> (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/utils.js:124:12)
  at Unzip.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickDomainCallback (node.js:381:11)
error: To report the above error, follow the guide at: http://docpad.org/bug-report
info: Shutting down... cya next time!
```

**Comment by ezmiller** [comment]
Never mind. I forgot to run `docpad init`
