### ISSUE TITLE
user/.docpad.cson error after upgrading

### ISSUE THREAD

**Issue by keikreutler** [docpad/docpad#934]
Hi,

I was having trouble with my docpad projects related to a CSON error; I ended up deleting all instances of node, npm, and docpad and reinstalling each. After globally installing docpad@6.73, I can create new docpad projects (though they throw lengthy errors about cyclic.js?), but I can't run docpad in any of my existing projects. When I try docpad update, docpad upgrade, docpad run in preexisting projects, I receive the following error:

    error: undefined '/Users/keikreutler/.docpad.cson'
    error: null
    error: null 
    TypeError: undefined is not a function
      at Object.exports.eval (/Users/keikreutler/Development/git/aporia/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/coffee-script.js:133:47)
      at CSON.parseSync (/Users/keikreutler/Development/git/aporia/node_modules/docpad/node_modules/cson/out/lib/cson.js:105:34)
      at ambi (/Users/keikreutler/Development/git/aporia/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:57:27)
      at [object Object]._onTimeout (/Users/keikreutler/Development/git/aporia/node_modules/docpad/node_modules/cson/out/lib/cson.js:89:18)
      at Timer.listOnTimeout (timers.js:110:15)
    error: null
    info: null

I tried installing the docpad-plugin-cson globally but it didn't help. Any suggestions?

Let me know if I can clarify anything, and thank you for all your work on docpad!

**Comment by balupton** [comment]
I think I experienced this, try the following:

```
npm i -g docked
docpad update --global
```

**Comment by keikreutler** [comment]
Thanks, tried this, and I can run docpad in most projects now, and did a few fresh installs in empty directories and moved over the src files for the few that didn't work. Appreciate the help!

**Comment by Altalus** [comment]
Thank you @balupton, it fixed my install :+1:
