### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by dimitarkolev** [docpad/docpad#935]
TypeError: Object #<_Class> has no method 'getTotals'
  at _Class.<anonymous> (/home/dick/Projects/acherno/web-next/node_modules/docpad/out/lib/docpad.js:1023:30)
  at _Class.emit (events.js:95:17)
  at _Class.TaskGroup.addItem (/home/dick/Projects/acherno/web-next/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:742:12)
  at _Class.TaskGroup.addTask (/home/dick/Projects/acherno/web-next/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:789:19)
  at DocPad.generate (/home/dick/Projects/acherno/web-next/node_modules/docpad/out/lib/docpad.js:3293:7)
  at ambi (/home/dick/Projects/acherno/web-next/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:55:18)
  at fireMethod (/home/dick/Projects/acherno/web-next/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:385:23)
  at b (domain.js:183:18)
  at Domain.run (domain.js:123:23)
  at Task.fire (/home/dick/Projects/acherno/web-next/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:423:27)
  at Object._onImmediate (/home/dick/Projects/acherno/web-next/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:440:26)
  at processImmediate [as _immediateCallback] (timers.js:345:15)

Any suggestion will be appreciated

**Comment by Lisa-Williams** [comment]
Exact same error message here when I compile the Semantic-UI docs.
```Text
[gulp] Created: ..\docs\out\src\themes\twitter\elements\button.overrides
[gulp] Created: ..\docs\out\src\themes\twitter\elements\button.variables

C:\Users\Lisa\devdocs\semanticui\ui> cd ..\docs

C:\Users\Lisa\devdocs\semanticui\docs> docpad run
info: Welcome to DocPad v6.73.4 (local installation: C:\Users\Lisa\devdocs\semanticui\docs\node_modules\docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: eco, ghpages, partials
info: Environment: development
info: DocPad listening to http://127.0.0.1:9778/ on directory C:\Users\Lisa\devdocs\semanticui\docs\out
TypeError: Object #<_Class> has no method 'getTotals'
  at _Class.<anonymous> (C:\Users\Lisa\devdocs\semanticui\docs\node_modules\docpad\out\lib\docpad.js:1023:30)
  at _Class.emit (events.js:95:17)
  at _Class.TaskGroup.addItem (C:\Users\Lisa\devdocs\semanticui\docs\node_modules\docpad\node_modules\taskgroup\out\lib\taskgroup.js:742:12)
  at _Class.TaskGroup.addTask (C:\Users\Lisa\devdocs\semanticui\docs\node_modules\docpad\node_modules\taskgroup\out\lib\taskgroup.js:789:19)
  at DocPad.generate (C:\Users\Lisa\devdocs\semanticui\docs\node_modules\docpad\out\lib\docpad.js:3293:7)
  at Task.<anonymous> (C:\Users\Lisa\devdocs\semanticui\docs\node_modules\docpad\node_modules\bal-util\out\lib\flow.js:42:21)
  at ambi (C:\Users\Lisa\devdocs\semanticui\docs\node_modules\docpad\node_modules\ambi\out\lib\ambi.js:55:18)
  at fireMethod (C:\Users\Lisa\devdocs\semanticui\docs\node_modules\docpad\node_modules\taskgroup\out\lib\taskgroup.js:385:23)
  at b (domain.js:183:18)
  at Domain.run (domain.js:123:23)
  at Task.fire (C:\Users\Lisa\devdocs\semanticui\docs\node_modules\docpad\node_modules\taskgroup\out\lib\taskgroup.js:423:27)
  at Object._onImmediate (C:\Users\Lisa\devdocs\semanticui\docs\node_modules\docpad\node_modules\taskgroup\out\lib\taskgroup.js:440:26)

  at processImmediate [as _immediateCallback] (timers.js:354:15)

C:\Users\Lisa\devdocs\semanticui\docs>
```

**Comment by balupton** [comment]
Seems it's a caching issue. Try:

```
npm install -g docpad
rm -Rf node_modules
npm install
```

**Comment by Lisa-Williams** [comment]
I might be wrong. But I'm running the **local** copy of Docpad.
Inside ```C:\Users\Lisa\devdocs\semanticui\docs```

Also ``` npm cache clean``` will clear out the entire npm cache folder. Not just Docpad's subpath. in the npm cache.

**Comment by Lisa-Williams** [comment]
Also, where is ```getTotals()``` defined?
I just searched this repo and it's only used/called, and not defined.
Shouldn't it be in one of Docpad's dependencies/plugins? -----> ```docpad-plugin-redirector```?
Which is not referenced (anymore?) in Docpad's ```package.json``` file.

I'm sorry but I'm just trying to find out what's going on.

**Comment by balupton** [comment]
No worries. So for some reason I suspect that DocPad instead of requiring it's TaskGroup requirement (v4.2.1 I believe) is requiring an old version - likely an npm cache issue.

Perhaps as well, before the commands above, I'd suggest doing `npm install -g npm` to make sure npm is the latest.

**Comment by Lisa-Williams** [comment]
The `Taskgroup module had been upgraded to version 4.2.1

**Comment by balupton** [comment]
Can you try the earlier commands for arguments sake then?

If it fails, I'll happily remote into your machine if you'd like and investigate further :-)

**Comment by balupton** [comment]
@Lisa-Williams just experienced this, fixing now.

**Comment by balupton** [comment]
@Lisa-Williams v6.73.5 now out with hopefully a fix for this, thanks for the report both of you

**Comment by Lisa-Williams** [comment]
@balupton I just retried with just ```docpad upgrade```, and ```docpad update``` to get ```v6.73.5```  and it worked. No more errors. Thanks!

Hope that this also works out well for @dimitarkolev

**Comment by dimitarkolev** [comment]
Yes it does :)

**Comment by Lisa-Williams** [comment]
Cool! \0/
