### ISSUE TITLE
ReferenceError: queryEngine is not defined

### ISSUE THREAD

**Issue by wlbrough** [docpad/docpad#943]
Node v0.10.33, npm 2.7.1, Docpad v6.78.0
Windows 7 64-bit, Lenovo Laptop

When I attempt docpad run in an empty directory, this error is generated.

ReferenceError: queryEngine is not defined 
  at DocPad.getSkeletons (C:\Program Files\nodejs\node_modules\docpad\out\lib\docpad.js:650:45)
  at DocPad.selectSkeleton (C:\Program Files\nodejs\node_modules\docpad\out\lib\docpad.js:4242:14)
  at C:\Program Files\nodejs\node_modules\docpad\out\lib\docpad.js:4279:23
  at C:\Program Files\nodejs\node_modules\docpad\out\lib\docpad.js:4263:16
  at Object.cb [as oncomplete] (evalmachine.<anonymous>:168:19)

**Comment by balupton** [comment]
Fixed in v6.78.1.
