### ISSUE TITLE
docpad run should ignore .git directory when checking for empty directory

### ISSUE THREAD

**Issue by WalkerCodeRanger** [docpad/docpad#979]
I tried to run `docpad run` in my directory and it refused to apply a skeleton because it said the directory was not empty. The only thing in it was my `.git` directory.  I can understand why the directory needs to be empty to apply the skeleton since the skeleton could have any sort of file, even .gitignore etc.  But the skeleton should never have a `.git` directory right? So ignoring it should be safe.

**Comment by balupton** [comment]
Skeletons work by cloning git repositories, hence the requirement for a completely empty directory.

**Comment by cjs-cynic-net** [comment]
Well, you need to explain to people about this, especially because it breaks in very non-intuitive ways for git users. Here's what, more or less, my first try at using docpad looked like:

```
telephonic $ mkdir z
telephonic $ cd z
telephonic $ git init
Initialized empty Git repository in /home/cjs/z/.git/
telephonic $ docpad run
info: Welcome to DocPad v6.78.4 (global installation: /home/cjs/local/lib/node_modules/docpad)
notice: Please donate to DocPad or have your company sponsor it: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: 
info: Environment: development
warning: A warning occured:

Error: We couldn't find an existing DocPad project inside your current directory. Looked at: /home/cjs/z
If you're wanting to use a pre-made skeleton for the basis of your new project, then run DocPad again inside an empty directory.
If you're wanting to start your new project from scratch, then refer to the Getting Started guide here:
    http://docpad.org/docs/start
For more information about what this means, visit:
    http://docpad.org/troubleshoot
  at DocPad.warn (/home/cjs/local/lib/node_modules/docpad/out/lib/docpad.js:3427:52)
  at /home/cjs/local/lib/node_modules/docpad/out/lib/docpad.js:5501:20
  at /home/cjs/local/lib/node_modules/docpad/node_modules/graceful-fs/graceful-fs.js:140:16
  at FSReqWrap.oncomplete (fs.js:83:15)

To report the above, follow the guide at: http://docpad.org/bug-report
info: The action completed successfully
```
