### ISSUE TITLE
docpad upgrade removed my NPM installation & docpad executable.

### ISSUE THREAD

**Issue by giantelk** [docpad/docpad#990]
`docpad upgrade` removed my NPM installation & also removed the `docpad` executable. See output below, trying to get Semantic UI docs set up: 
https://github.com/Semantic-Org/Semantic-UI-Docs

As per: 
```
npm install -g docpad
docpad install eco
docpad update 
docpad upgrade
```

users-MacBook-Pro:Semantic-UI-Docs carlf$ sudo npm install -g docpad
Password:

```
 
> ambi@2.2.0 preinstall /usr/local/lib/node_modules/docpad/node_modules/ambi
> node ./cyclic.js

 
> typechecker@2.0.8 preinstall /usr/local/lib/node_modules/docpad/node_modules/typechecker
> node ./cyclic.js

 
> safefs@3.1.3 preinstall /usr/local/lib/node_modules/docpad/node_modules/safefs
> node ./cyclic.js

 
> safeps@4.0.0 preinstall /usr/local/lib/node_modules/docpad/node_modules/safeps
> node ./cyclic.js

 
> safeps@3.0.2 preinstall /usr/local/lib/node_modules/docpad/node_modules/lazy-require/node_modules/safeps
> node ./cyclic.js

 
> taskgroup@4.3.0 preinstall /usr/local/lib/node_modules/docpad/node_modules/taskgroup
> node ./cyclic.js

/usr/local/bin/docpad -> /usr/local/lib/node_modules/docpad/bin/docpad
/usr/local/bin/docpad-debug -> /usr/local/lib/node_modules/docpad/bin/docpad-debug
/usr/local/bin/docpad-server -> /usr/local/lib/node_modules/docpad/bin/docpad-server
/usr/local/bin/docpad-compile -> /usr/local/lib/node_modules/docpad/bin/docpad-compile
/usr/local/bin/docpad-trace -> /usr/local/lib/node_modules/docpad/bin/docpad-trace
docpad@6.78.1 /usr/local/lib/node_modules/docpad
├── extendr@2.1.0
├── csextends@1.0.3
├── caterpillar-filter@2.0.3
├── event-emitter-grouped@2.4.3
├── extract-opts@3.0.1
├── envfile@1.0.0
├── ambi@2.2.0
├── eachr@2.0.4
├── scandirectory@2.5.0
├── typechecker@2.0.8
├── mime@1.3.4
├── safeps@4.0.0
├── underscore@1.8.3
├── getmac@1.0.7 (extract-opts@2.2.0)
├── ignorefs@1.0.0 (ignorepatterns@1.0.1)
├── istextorbinary@1.0.2 (binaryextensions@1.0.0, textextensions@1.0.1)
├── caterpillar-human@2.1.2 (ansistyles@0.1.3, ansicolors@0.3.2)
├── progressbar@1.0.3 (progress@1.1.2)
├── watchr@2.4.13 (extract-opts@2.2.0)
├── backbone@1.1.2
├── bal-util@2.5.1 (extract-opts@2.2.0)
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── lazy-require@2.0.0 (safeps@3.0.2)
├── semver@4.3.6
├── safefs@3.1.3 (graceful-fs@3.0.8)
├── method-override@2.3.5 (methods@1.1.1, vary@1.0.1, parseurl@1.3.0, debug@2.2.0)
├── promptly@0.2.1 (read@1.0.6)
├── caterpillar@2.0.9 (readable-stream@1.1.13)
├── taskgroup@4.3.0
├── encoding@0.1.11 (iconv-lite@0.4.11)
├── jschardet@1.1.1
├── rimraf@2.4.2 (glob@5.0.14)
├── superagent@1.3.0 (extend@1.2.1, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, qs@2.3.3, debug@2.2.0, readable-stream@1.0.27-1, formidable@1.0.14, form-data@0.2.0)
├── cson@3.0.1 (requirefresh@2.0.0, coffee-script@1.9.3, cson-parser@1.1.1)
├── query-engine@1.5.7
├── express@3.21.2 (escape-html@1.0.2, merge-descriptors@1.0.0, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.2, vary@1.0.1, basic-auth@1.0.3, etag@1.7.0, content-type@1.0.1, parseurl@1.3.0, content-disposition@0.5.0, commander@2.6.0, depd@1.0.1, debug@2.2.0, proxy-addr@1.0.8, mkdirp@0.5.1, send@0.13.0, connect@2.30.2)
└── yamljs@0.2.3 (benchmark@1.0.0, glob@4.5.3, argparse@0.1.16, coffeeify@0.7.0, jasmine-node@1.14.5)
users-MacBook-Pro:Semantic-UI-Docs carlf$ docpad
users-MacBook-Pro:Semantic-UI-Docs carlf$ docpad
users-MacBook-Pro:Semantic-UI-Docs carlf$ docpad -help

  error: option `-p, --port <port>' argument missing

An error occured within the child DocPad instance: Command exited with a non-zero status code.
users-MacBook-Pro:Semantic-UI-Docs carlf$ docpad --help

  Usage: docpad [options] [command]


  Commands:

    action <actions>        does everything: skeleton, generate, watch, server
    init                    initialize your directory with an empty docpad project
    run                     does everything: skeleton, generate, watch, server
    server                  creates a server for your generated project
    render [path]           render the file at <path> and output its results to stdout
    generate                (re)generates your project
    watch                   watches your project for changes, and (re)generates whenever a change is made
    update                  update your local DocPad and plugin installations to their latest compatible version
    upgrade                 upgrade your global DocPad and NPM installations to the latest
    install [pluginName]    install plugins
    uninstall <pluginName>  uninstall a plugin
    clean                   ensure everything is cleaned correctly (will remove your out directory)
    info                    display the information about your docpad instance
    help                    output the help
    *                       anything else outputs the help

  Options:

    -h, --help                 output usage information
    -V, --version              output the version number
    -o, --out <outPath>        where to output the rendered files (to a directory) or file (to an output file)
    -c, --config <configPath>  a custom configuration file to load in
    -e, --env <environment>    the environment name to use for this instance, multiple names can be separated with a comma
    -d, --debug [logLevel]     the level of debug messages you would like to display, if specified defaults to 7, otherwise 6
    -g, --global               whether or not we should just fire the global installation of docpad
    -f, --force                force a re-install of all modules
    --no-color                 don't colorize terminal output
    -p, --port <port>          a custom port to use for the server <port>
    --cache                    use the database cache ability to speed up docpad
    --silent                   don't use any prompts
    --skeleton <skeleton>      specify the id of a skeleton to use instead of prompting
    --profile                  enable profiling
    --offline                  don't do any remote requests

users-MacBook-Pro:Semantic-UI-Docs carlf$ docpad install eco
info: Welcome to DocPad v6.78.1 (local installation: /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: eco, ghpages, partials
info: Environment: development
docpad-plugin-eco@2.1.0 node_modules/docpad-plugin-eco
└── eco@1.1.0-rc-3 (strscan@1.0.1, coffee-script@1.9.3)
npm WARN package.json Dependency 'docpad' exists in both dependencies and devDependencies, using 'docpad@~6.78.1' from dependencies
npm WARN package.json Dependency 'docpad-plugin-eco' exists in both dependencies and devDependencies, using 'docpad-plugin-eco@^2.1.0' from dependencies
npm WARN package.json Dependency 'docpad-plugin-ghpages' exists in both dependencies and devDependencies, using 'docpad-plugin-ghpages@~2.4.4' from dependencies

> phantomjs@1.9.18 install /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/phantomjs
> node install.js

Download already available at /var/folders/bj/yp0g5p0s7f55gf1wc994553m0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Extracting zip contents
Removing /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/bj/yp0g5p0s7f55gf1wc994553m0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1439684445384/phantomjs-1.9.8-macosx -> /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/phantomjs/lib/phantom/bin/phantomjs
info: The action completed successfully
info: Shutting down... cya next time!
users-MacBook-Pro:Semantic-UI-Docs carlf$ npm

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, prefix, prune, publish, r, rb, rebuild, remove, repo,
    restart, rm, root, run-script, s, se, search, set, show,
    shrinkwrap, star, stars, start, stop, t, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, upgrade,
    v, verison, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/carlf/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.11.3 /usr/local/lib/node_modules/npm
users-MacBook-Pro:Semantic-UI-Docs carlf$ 
users-MacBook-Pro:Semantic-UI-Docs carlf$ 
users-MacBook-Pro:Semantic-UI-Docs carlf$ 
users-MacBook-Pro:Semantic-UI-Docs carlf$ 
users-MacBook-Pro:Semantic-UI-Docs carlf$ 
users-MacBook-Pro:Semantic-UI-Docs carlf$ docpad update
info: Welcome to DocPad v6.78.1 (local installation: /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: eco, ghpages, partials
info: Environment: development
info: Cleaning files
info: Cleaned files
 
> safefs@3.1.3 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-ghpages/node_modules/safefs
> node ./cyclic.js

 
> safeps@2.2.13 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-ghpages/node_modules/safeps
> node ./cyclic.js

 
> taskgroup@4.3.0 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-ghpages/node_modules/taskgroup
> node ./cyclic.js

\
> typechecker@2.0.8 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-ghpages/node_modules/safeps/node_modules/typechecker
> node ./cyclic.js

 
> ambi@2.2.0 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-ghpages/node_modules/taskgroup/node_modules/ambi
> node ./cyclic.js

 
> ambi@2.2.0 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad/node_modules/ambi
> node ./cyclic.js

 
> typechecker@2.0.8 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad/node_modules/typechecker
> node ./cyclic.js

 
> safefs@3.1.3 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad/node_modules/safefs
> node ./cyclic.js

 
> safeps@4.0.0 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad/node_modules/safeps
> node ./cyclic.js

 
> typechecker@2.0.8 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-ghpages/node_modules/taskgroup/node_modules/ambi/node_modules/typechecker
> node ./cyclic.js

 
> safeps@3.0.2 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad/node_modules/lazy-require/node_modules/safeps
> node ./cyclic.js

 
> taskgroup@4.3.0 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad/node_modules/taskgroup
> node ./cyclic.js

docpad-plugin-eco@2.1.0 node_modules/docpad-plugin-eco
└── eco@1.1.0-rc-3 (strscan@1.0.1, coffee-script@1.9.3)

docpad-plugin-ghpages@2.4.4 node_modules/docpad-plugin-ghpages
├── safeps@2.2.13 (extract-opts@2.2.0, typechecker@2.0.8)
├── safefs@3.1.3 (graceful-fs@3.0.8)
├── taskgroup@4.3.0 (csextends@1.0.3, ambi@2.2.0)
└── rimraf@2.4.2 (glob@5.0.14)

docpad@6.78.1 node_modules/docpad
├── csextends@1.0.3
├── extendr@2.1.0
├── caterpillar-filter@2.0.3
├── event-emitter-grouped@2.4.3
├── extract-opts@3.0.1
├── envfile@1.0.0
├── ambi@2.2.0
├── eachr@2.0.4
├── scandirectory@2.5.0
├── typechecker@2.0.8
├── mime@1.3.4
├── safeps@4.0.0
├── underscore@1.8.3
├── getmac@1.0.7 (extract-opts@2.2.0)
├── ignorefs@1.0.0 (ignorepatterns@1.0.1)
├── istextorbinary@1.0.2 (binaryextensions@1.0.0, textextensions@1.0.1)
├── progressbar@1.0.3 (progress@1.1.2)
├── caterpillar-human@2.1.2 (ansistyles@0.1.3, ansicolors@0.3.2)
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── backbone@1.1.2
├── watchr@2.4.13 (extract-opts@2.2.0)
├── bal-util@2.5.1 (extract-opts@2.2.0)
├── lazy-require@2.0.0 (safeps@3.0.2)
├── safefs@3.1.3 (graceful-fs@3.0.8)
├── semver@4.3.6
├── method-override@2.3.5 (methods@1.1.1, vary@1.0.1, parseurl@1.3.0, debug@2.2.0)
├── promptly@0.2.1 (read@1.0.6)
├── caterpillar@2.0.9 (readable-stream@1.1.13)
├── taskgroup@4.3.0
├── encoding@0.1.11 (iconv-lite@0.4.11)
├── rimraf@2.4.2 (glob@5.0.14)
├── jschardet@1.1.1
├── superagent@1.3.0 (extend@1.2.1, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, qs@2.3.3, debug@2.2.0, readable-stream@1.0.27-1, formidable@1.0.14, form-data@0.2.0)
├── cson@3.0.1 (requirefresh@2.0.0, coffee-script@1.9.3, cson-parser@1.1.1)
├── query-engine@1.5.7
├── express@3.21.2 (escape-html@1.0.2, merge-descriptors@1.0.0, cookie@0.1.3, utils-merge@1.0.0, methods@1.1.1, cookie-signature@1.0.6, fresh@0.3.0, range-parser@1.0.2, vary@1.0.1, basic-auth@1.0.3, etag@1.7.0, content-type@1.0.1, parseurl@1.3.0, content-disposition@0.5.0, commander@2.6.0, depd@1.0.1, debug@2.2.0, proxy-addr@1.0.8, mkdirp@0.5.1, send@0.13.0, connect@2.30.2)
└── yamljs@0.2.3 (benchmark@1.0.0, glob@4.5.3, argparse@0.1.16, coffeeify@0.7.0, jasmine-node@1.14.5)
 
> safefs@3.1.3 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-ghpages/node_modules/safefs
> node ./cyclic.js

 
> safeps@2.2.13 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-ghpages/node_modules/safeps
> node ./cyclic.js

 
> taskgroup@4.3.0 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-partials/node_modules/taskgroup
> node ./cyclic.js

 
> taskgroup@4.3.0 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-ghpages/node_modules/taskgroup
> node ./cyclic.js

 
> typechecker@2.0.8 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-ghpages/node_modules/safeps/node_modules/typechecker
> node ./cyclic.js

 
> typechecker@2.0.8 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-partials/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js

 
> ambi@2.2.0 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-ghpages/node_modules/taskgroup/node_modules/ambi
> node ./cyclic.js

 
> ambi@2.2.0 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-partials/node_modules/taskgroup/node_modules/ambi
> node ./cyclic.js

 
> typechecker@2.0.8 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-ghpages/node_modules/taskgroup/node_modules/ambi/node_modules/typechecker
> node ./cyclic.js

 
> typechecker@2.0.8 preinstall /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad-plugin-partials/node_modules/taskgroup/node_modules/ambi/node_modules/typechecker
> node ./cyclic.js

docpad-plugin-eco@2.1.0 node_modules/docpad-plugin-eco
└── eco@1.1.0-rc-3 (strscan@1.0.1, coffee-script@1.9.3)

docpad-plugin-partials@2.9.2 node_modules/docpad-plugin-partials
├── extendr@2.1.0 (typechecker@2.0.8)
└── taskgroup@4.3.0 (csextends@1.0.3, ambi@2.2.0)

docpad-plugin-ghpages@2.4.4 node_modules/docpad-plugin-ghpages
├── safefs@3.1.3 (graceful-fs@3.0.8)
├── safeps@2.2.13 (extract-opts@2.2.0, typechecker@2.0.8)
├── taskgroup@4.3.0 (csextends@1.0.3, ambi@2.2.0)
└── rimraf@2.4.2 (glob@5.0.14)
npm WARN package.json Dependency 'docpad' exists in both dependencies and devDependencies, using 'docpad@~6.78.1' from dependencies
npm WARN package.json Dependency 'docpad-plugin-eco' exists in both dependencies and devDependencies, using 'docpad-plugin-eco@~2.1.0' from dependencies
npm WARN package.json Dependency 'docpad-plugin-ghpages' exists in both dependencies and devDependencies, using 'docpad-plugin-ghpages@~2.4.4' from dependencies

> phantomjs@1.9.18 install /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/phantomjs
> node install.js

Download already available at /var/folders/bj/yp0g5p0s7f55gf1wc994553m0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Extracting zip contents
Removing /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/bj/yp0g5p0s7f55gf1wc994553m0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1439684488264/phantomjs-1.9.8-macosx -> /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/phantomjs/lib/phantom/bin/phantomjs
info: The action completed successfully
info: Shutting down... cya next time!
users-MacBook-Pro:Semantic-UI-Docs carlf$ docpad upgrade
info: Welcome to DocPad v6.78.1 (local installation: /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: eco, ghpages, partials
info: Environment: development
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "npm@latest" "docpad@6" "--global"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /usr/local/lib/node_modules/docpad
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, rmdir '/usr/local/lib/node_modules/docpad'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/docpad']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/docpad' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, rmdir '/usr/local/lib/node_modules/docpad'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/docpad']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/docpad' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/carlf/Documents/dev/open source/Semantic-UI-Docs/npm-debug.log
error: The action completed successfully
error: An error occured:

Error: Command exited with a non-zero status code.
  at Object.safeps.prepareExecutableResult (/Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad/node_modules/safeps/out/lib/safeps.js:197:24)
  at ChildProcess.<anonymous> (/Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad/node_modules/safeps/out/lib/safeps.js:329:29)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1015:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

To report the above, follow the guide at: http://docpad.org/bug-report
Error: Command exited with a non-zero status code.
  at Object.safeps.prepareExecutableResult (/Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad/node_modules/safeps/out/lib/safeps.js:197:24)
  at ChildProcess.<anonymous> (/Users/carlf/Documents/dev/open source/Semantic-UI-Docs/node_modules/docpad/node_modules/safeps/out/lib/safeps.js:329:29)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1015:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
users-MacBook-Pro:Semantic-UI-Docs carlf$ npm
-bash: /usr/local/bin/npm: No such file or directory
users-MacBook-Pro:Semantic-UI-Docs carlf$ docpad
-bash: /usr/local/bin/docpad: No such file or directory
users-MacBook-Pro:Semantic-UI-Docs carlf$ 

```

**Comment by balupton** [comment]
`docpad upgrade` runs `npm install -g npm && npm install -g docpad` more or less - the issue that would have occurred is that it try to run this, but your machines global npm requires sudo to install things - strange that it nuked it, at is just those commands that run.

sudo with npm is a common pain point, and an avoidable pain point - it's only a matter of time until one runs into permissions errors with it - hence why we only recommend using node version manager in our [supported node install docs](http://learn.bevry.me/node/install/), and have warnings about sudo on our install page: http://docpad.org/docs/install/

**Comment by giantelk** [comment]
It's the 1st time I've seen a command that needs sudo NOT show me a warning
in the console. What ever is deleting my npm install is a bad, bad bug.

On Sun, Aug 16, 2015 at 3:49 AM, Benjamin Lupton <notifications@github.com>
wrote:

> docpad upgrade runs npm install -g npm && npm install -g docpad more or
> less - the issue that would have occurred is that it try to run this, but
> your machines global npm requires sudo to install things - strange that it
> nuked it, at is just those commands that run.
>
> sudo with npm is a common pain point, and an avoidable pain point - it's
> only a matter of time until one runs into permissions errors with it -
> hence why we only recommend using node version manager in our supported
> node install docs <http://learn.bevry.me/node/install/>, and have
> warnings about sudo on our install page: http://docpad.org/docs/install/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docpad/docpad/issues/990#issuecomment-131497715>.
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by balupton** [comment]
Replaced with https://github.com/docpad/docpad/issues/1009
